// Plan PDF Export — generates a printable HTML page for active plan details

import { getActivePlan, getPlanById, getPlanProgress, type ActivePlan } from './event-plan-service';
import { getProfile } from './store';

function buildPlanHTML(plan: ActivePlan): string {
  const meta = getPlanById(plan.planId);
  const progress = getPlanProgress();
  const profile = getProfile();

  const endDate = new Date(plan.startDate);
  endDate.setDate(endDate.getDate() + plan.duration);

  const dayRows = Array.from({ length: plan.duration }, (_, i) => {
    const d = new Date(plan.startDate);
    d.setDate(d.getDate() + i);
    const dateStr = d.toLocaleDateString('en-IN', { weekday: 'short', month: 'short', day: 'numeric' });
    const isRefeed = plan.planId === 'celebrity_transformation' && i + 1 === 10;
    const cal = isRefeed ? (profile?.tdee || plan.dailyCalories) : plan.dailyCalories;
    const carbs = isRefeed ? Math.round(plan.dailyCarbs * 1.5) : plan.dailyCarbs;
    const note = isRefeed ? '🔄 Refeed Day' : '';
    const isPast = progress && i + 1 < progress.dayNumber;
    return `<tr style="${isPast ? 'opacity:0.5' : ''}">
      <td style="padding:6px 10px;border-bottom:1px solid #eee">${i + 1}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee">${dateStr}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee;font-weight:600">${cal}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee">${plan.dailyProtein}g</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee">${carbs}g</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee">${plan.dailyFat}g</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee;color:#888">${note}</td>
    </tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>${meta?.name || 'Plan'} — NutriLens AI</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; color: #1a1a1a; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  .subtitle { color: #666; font-size: 13px; margin-bottom: 24px; }
  .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }
  .summary-card { background: #f7f7f7; border-radius: 12px; padding: 14px; text-align: center; }
  .summary-card .value { font-size: 22px; font-weight: 700; }
  .summary-card .label { font-size: 11px; color: #888; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; padding: 8px 10px; border-bottom: 2px solid #333; font-size: 11px; text-transform: uppercase; color: #555; }
  .rules { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 20px; }
  .rule { background: #e8f5e9; color: #2e7d32; padding: 4px 10px; border-radius: 20px; font-size: 11px; font-weight: 600; }
  .footer { margin-top: 30px; text-align: center; color: #aaa; font-size: 11px; }
  @media print { body { padding: 0; } }
</style>
</head><body>
<h1>${meta?.emoji || '🎯'} ${meta?.name || 'Active Plan'}</h1>
<p class="subtitle">${profile?.name || 'User'} · ${plan.duration} days · ${new Date(plan.startDate).toLocaleDateString('en-IN')} → ${endDate.toLocaleDateString('en-IN')}</p>

<div class="summary">
  <div class="summary-card"><div class="value">${plan.dailyCalories}</div><div class="label">Daily Calories</div></div>
  <div class="summary-card"><div class="value">${plan.dailyProtein}g</div><div class="label">Protein</div></div>
  <div class="summary-card"><div class="value">${plan.dailyCarbs}g</div><div class="label">Carbs</div></div>
  <div class="summary-card"><div class="value">${plan.dailyFat}g</div><div class="label">Fat</div></div>
</div>

${meta?.rules ? `<div class="rules">${meta.rules.map(r => `<span class="rule">${r}</span>`).join('')}</div>` : ''}

<table>
  <thead><tr><th>Day</th><th>Date</th><th>Calories</th><th>Protein</th><th>Carbs</th><th>Fat</th><th>Note</th></tr></thead>
  <tbody>${dayRows}</tbody>
</table>

<p class="footer">Generated by NutriLens AI · ${new Date().toLocaleDateString('en-IN')}</p>
</body></html>`;
}

export function exportPlanPDF(): void {
  const plan = getActivePlan();
  if (!plan) return;

  const html = buildPlanHTML(plan);
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 500);
}
