import { estimateRecipeCost } from './recipe-cost';

export interface Recipe {
  id: string;
  name: string;
  description: string;
  cuisine: string;
  mealType: ('breakfast' | 'lunch' | 'dinner' | 'snack')[];
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  prepTime: number; // minutes
  cookTime: number;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  servings: number;
  tags: string[];
  ingredients: { name: string; quantity: string; category: string }[];
  steps: string[];
  tips?: string;
  emoji: string;
  // Extended metadata
  estimatedCost?: number;
  suitableFor?: string[];
  avoidFor?: string[];
  nutritionScore?: number;
  volumeFactor?: number; // 1-5 (1=low volume like chips, 5=high volume like soup)
}

export interface EnrichedRecipe extends Recipe {
  estimatedCost: number;
  nutritionScore: number;
  satietyScore: number;
  proteinPerRupee: number;
}

/** Compute enriched metadata for a recipe (cost + nutrition + satiety) */
export function getEnrichedRecipe(recipe: Recipe): EnrichedRecipe {
  const estimatedCost = recipe.estimatedCost ?? estimateRecipeCost(recipe);
  const proteinPerCal = recipe.calories > 0 ? (recipe.protein / recipe.calories) * 100 : 0;
  const fiberBonus = Math.min(recipe.fiber || 0, 10);
  const nutritionScore = recipe.nutritionScore ?? Math.min(10, Math.round(proteinPerCal * 1.5 + fiberBonus * 0.3));
  const vf = recipe.volumeFactor ?? 2;
  const satietyScore = (recipe.protein / 10) + ((recipe.fiber || 0) / 5) + (vf / 2);
  const proteinPerRupee = estimatedCost > 0 ? recipe.protein / estimatedCost : 0;
  return { ...recipe, estimatedCost, nutritionScore, satietyScore, proteinPerRupee };
}

export const recipes: Recipe[] = [
  // ========== INDIAN BREAKFAST ==========
  {
    id: 'idli-sambar',
    name: 'Idli with Sambar',
    description: 'Steamed rice cakes with lentil vegetable stew – a South Indian classic.',
    cuisine: 'Indian',
    mealType: ['breakfast'],
    calories: 280,
    protein: 10,
    carbs: 52,
    fat: 4,
    fiber: 6,
    prepTime: 10,
    cookTime: 20,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'low-fat', 'high-fiber', 'south-indian'],
    ingredients: [
      { name: 'Idli batter', quantity: '1 cup', category: 'Grains' },
      { name: 'Toor dal', quantity: '1/4 cup', category: 'Pulses' },
      { name: 'Mixed vegetables', quantity: '1/2 cup', category: 'Produce' },
      { name: 'Sambar powder', quantity: '1 tsp', category: 'Spices' },
      { name: 'Tamarind paste', quantity: '1/2 tsp', category: 'Pantry' },
      { name: 'Mustard seeds', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Curry leaves', quantity: '5-6', category: 'Produce' },
    ],
    steps: [
      'Pour idli batter into greased idli moulds.',
      'Steam for 10-12 minutes until a toothpick comes out clean.',
      'Cook toor dal with turmeric until soft.',
      'Sauté vegetables, add sambar powder and tamarind.',
      'Combine with cooked dal and simmer for 5 minutes.',
      'Temper with mustard seeds and curry leaves.',
    ],
    tips: 'Use overnight-fermented batter for fluffier idlis.',
    emoji: '🫓',
  },
  {
    id: 'poha',
    name: 'Poha (Flattened Rice)',
    description: 'Spiced flattened rice with peanuts, onions, and fresh coriander.',
    cuisine: 'Indian',
    mealType: ['breakfast'],
    calories: 310,
    protein: 7,
    carbs: 48,
    fat: 10,
    fiber: 3,
    prepTime: 5,
    cookTime: 10,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'quick', 'indian'],
    ingredients: [
      { name: 'Thick poha', quantity: '1 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 medium', category: 'Produce' },
      { name: 'Peanuts', quantity: '2 tbsp', category: 'Nuts' },
      { name: 'Turmeric powder', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Green chili', quantity: '1', category: 'Produce' },
      { name: 'Lemon juice', quantity: '1 tbsp', category: 'Produce' },
      { name: 'Fresh coriander', quantity: '2 tbsp', category: 'Produce' },
      { name: 'Oil', quantity: '1 tsp', category: 'Pantry' },
    ],
    steps: [
      'Rinse poha in water and drain. Set aside for 5 minutes.',
      'Heat oil, roast peanuts until golden. Remove.',
      'Sauté mustard seeds, curry leaves, green chili, and onion.',
      'Add turmeric, salt, and the soaked poha. Mix gently.',
      'Cook covered for 2 minutes on low heat.',
      'Garnish with peanuts, coriander, and lemon juice.',
    ],
    tips: 'Don\'t over-soak the poha or it will become mushy.',
    emoji: '🍚',
  },
  {
    id: 'upma',
    name: 'Rava Upma',
    description: 'Savory semolina porridge with vegetables and tempered spices.',
    cuisine: 'Indian',
    mealType: ['breakfast'],
    calories: 290,
    protein: 8,
    carbs: 44,
    fat: 9,
    fiber: 4,
    prepTime: 5,
    cookTime: 15,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'quick', 'south-indian'],
    ingredients: [
      { name: 'Semolina (rava)', quantity: '1/2 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 small', category: 'Produce' },
      { name: 'Green peas', quantity: '2 tbsp', category: 'Produce' },
      { name: 'Carrots', quantity: '2 tbsp diced', category: 'Produce' },
      { name: 'Mustard seeds', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Urad dal', quantity: '1/2 tsp', category: 'Pulses' },
      { name: 'Ghee', quantity: '1 tsp', category: 'Dairy' },
      { name: 'Water', quantity: '1.5 cups', category: 'Pantry' },
    ],
    steps: [
      'Dry roast semolina until fragrant. Set aside.',
      'Heat ghee, add mustard seeds and urad dal.',
      'Sauté onions, peas, and carrots.',
      'Add water and bring to a boil.',
      'Slowly add roasted semolina while stirring continuously.',
      'Cook on low heat until water is absorbed. Garnish with coriander.',
    ],
    emoji: '🥣',
  },
  {
    id: 'moong-dal-chilla',
    name: 'Moong Dal Chilla',
    description: 'Protein-rich savory crepe made from ground moong dal.',
    cuisine: 'Indian',
    mealType: ['breakfast', 'snack'],
    calories: 220,
    protein: 14,
    carbs: 28,
    fat: 6,
    fiber: 5,
    prepTime: 10,
    cookTime: 10,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'high-protein', 'gluten-free'],
    ingredients: [
      { name: 'Moong dal (soaked)', quantity: '1/2 cup', category: 'Pulses' },
      { name: 'Onion', quantity: '2 tbsp chopped', category: 'Produce' },
      { name: 'Tomato', quantity: '2 tbsp chopped', category: 'Produce' },
      { name: 'Green chili', quantity: '1', category: 'Produce' },
      { name: 'Ginger', quantity: '1/2 inch', category: 'Produce' },
      { name: 'Oil', quantity: '1 tsp', category: 'Pantry' },
    ],
    steps: [
      'Soak moong dal for 4 hours. Drain and grind to a smooth batter.',
      'Mix in chopped onion, tomato, ginger, chili, and salt.',
      'Heat a non-stick pan, pour a ladleful and spread thin.',
      'Cook on medium heat until the bottom is golden.',
      'Flip and cook the other side for 1 minute.',
      'Serve hot with green chutney.',
    ],
    tips: 'Soak dal overnight for the smoothest batter.',
    emoji: '🥞',
  },
  {
    id: 'masala-oats',
    name: 'Masala Oats',
    description: 'Indian-spiced oats with vegetables – quick and nutritious.',
    cuisine: 'Indian',
    mealType: ['breakfast'],
    calories: 250,
    protein: 9,
    carbs: 38,
    fat: 7,
    fiber: 6,
    prepTime: 5,
    cookTime: 10,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'quick', 'high-fiber', 'healthy'],
    ingredients: [
      { name: 'Rolled oats', quantity: '1/2 cup', category: 'Grains' },
      { name: 'Mixed vegetables', quantity: '1/3 cup', category: 'Produce' },
      { name: 'Onion', quantity: '1 small', category: 'Produce' },
      { name: 'Cumin seeds', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Turmeric', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Green chili', quantity: '1', category: 'Produce' },
      { name: 'Water', quantity: '1 cup', category: 'Pantry' },
    ],
    steps: [
      'Heat oil, add cumin seeds and let them splutter.',
      'Add onions and green chili, sauté until soft.',
      'Add mixed vegetables and turmeric. Cook 2 minutes.',
      'Add water and bring to a boil.',
      'Add oats, stir well, and cook for 3-4 minutes.',
      'Season with salt and pepper. Garnish with coriander.',
    ],
    emoji: '🥣',
  },
  {
    id: 'paratha-curd',
    name: 'Aloo Paratha with Curd',
    description: 'Stuffed potato flatbread served with fresh yogurt.',
    cuisine: 'Indian',
    mealType: ['breakfast', 'lunch'],
    calories: 420,
    protein: 12,
    carbs: 56,
    fat: 16,
    fiber: 4,
    prepTime: 15,
    cookTime: 15,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['vegetarian', 'north-indian', 'comfort-food'],
    ingredients: [
      { name: 'Whole wheat flour', quantity: '1 cup', category: 'Grains' },
      { name: 'Potato', quantity: '2 medium boiled', category: 'Produce' },
      { name: 'Green chili', quantity: '1', category: 'Produce' },
      { name: 'Coriander', quantity: '2 tbsp', category: 'Produce' },
      { name: 'Ghee', quantity: '1 tbsp', category: 'Dairy' },
      { name: 'Curd', quantity: '1/2 cup', category: 'Dairy' },
      { name: 'Cumin powder', quantity: '1/2 tsp', category: 'Spices' },
    ],
    steps: [
      'Knead soft dough with wheat flour and water. Rest 15 minutes.',
      'Mash boiled potatoes with chili, coriander, cumin, and salt.',
      'Roll dough into small circles, stuff with potato filling.',
      'Seal edges and roll gently into a flat paratha.',
      'Cook on a hot tawa with ghee until golden on both sides.',
      'Serve hot with fresh curd and pickle.',
    ],
    emoji: '🫓',
  },
  // ========== INDIAN LUNCH ==========
  {
    id: 'dal-rice',
    name: 'Dal Tadka with Steamed Rice',
    description: 'Yellow lentils tempered with cumin and garlic, served with rice.',
    cuisine: 'Indian',
    mealType: ['lunch', 'dinner'],
    calories: 450,
    protein: 18,
    carbs: 72,
    fat: 8,
    fiber: 8,
    prepTime: 10,
    cookTime: 25,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'high-protein', 'comfort-food', 'north-indian'],
    ingredients: [
      { name: 'Toor dal', quantity: '1/2 cup', category: 'Pulses' },
      { name: 'Basmati rice', quantity: '3/4 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 medium', category: 'Produce' },
      { name: 'Tomato', quantity: '1 medium', category: 'Produce' },
      { name: 'Garlic', quantity: '3 cloves', category: 'Produce' },
      { name: 'Cumin seeds', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Turmeric', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Red chili powder', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Ghee', quantity: '1 tbsp', category: 'Dairy' },
    ],
    steps: [
      'Wash and pressure cook toor dal with turmeric and water for 3 whistles.',
      'Cook rice separately until fluffy.',
      'Heat ghee, add cumin seeds and sliced garlic until golden.',
      'Add onions and cook until translucent.',
      'Add tomatoes, red chili powder, and salt. Cook until soft.',
      'Add cooked dal and simmer for 5 minutes. Garnish with coriander.',
    ],
    tips: 'For creamier dal, mash it with a ladle while simmering.',
    emoji: '🍛',
  },
  {
    id: 'rajma-chawal',
    name: 'Rajma Chawal',
    description: 'Kidney bean curry in rich tomato gravy with steamed rice.',
    cuisine: 'Indian',
    mealType: ['lunch'],
    calories: 520,
    protein: 22,
    carbs: 78,
    fat: 12,
    fiber: 14,
    prepTime: 20,
    cookTime: 40,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['vegetarian', 'high-protein', 'high-fiber', 'north-indian'],
    ingredients: [
      { name: 'Rajma (kidney beans)', quantity: '1/2 cup dried', category: 'Pulses' },
      { name: 'Basmati rice', quantity: '3/4 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 large', category: 'Produce' },
      { name: 'Tomato', quantity: '2 medium', category: 'Produce' },
      { name: 'Ginger-garlic paste', quantity: '1 tbsp', category: 'Produce' },
      { name: 'Rajma masala', quantity: '1 tbsp', category: 'Spices' },
      { name: 'Oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Soak rajma overnight. Pressure cook until tender (5-6 whistles).',
      'Heat oil, sauté onions until deep golden.',
      'Add ginger-garlic paste and cook for 1 minute.',
      'Add chopped tomatoes and rajma masala. Cook until tomatoes break down.',
      'Add cooked rajma with its liquid. Simmer 15-20 minutes.',
      'Mash a few beans for thick gravy. Serve over steamed rice.',
    ],
    emoji: '🫘',
  },
  {
    id: 'chicken-curry-rice',
    name: 'Chicken Curry with Rice',
    description: 'Classic Indian chicken curry in aromatic onion-tomato gravy.',
    cuisine: 'Indian',
    mealType: ['lunch', 'dinner'],
    calories: 550,
    protein: 38,
    carbs: 58,
    fat: 16,
    fiber: 4,
    prepTime: 15,
    cookTime: 30,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['high-protein', 'non-veg', 'north-indian'],
    ingredients: [
      { name: 'Chicken', quantity: '200g', category: 'Meat' },
      { name: 'Basmati rice', quantity: '3/4 cup', category: 'Grains' },
      { name: 'Onion', quantity: '2 medium', category: 'Produce' },
      { name: 'Tomato', quantity: '2 medium', category: 'Produce' },
      { name: 'Ginger-garlic paste', quantity: '1 tbsp', category: 'Produce' },
      { name: 'Chicken masala', quantity: '1 tbsp', category: 'Spices' },
      { name: 'Yogurt', quantity: '2 tbsp', category: 'Dairy' },
      { name: 'Oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Marinate chicken with yogurt, turmeric, and salt for 30 minutes.',
      'Heat oil, sauté onions until deep golden brown.',
      'Add ginger-garlic paste, cook 1 minute.',
      'Add tomatoes and chicken masala, cook until oil separates.',
      'Add marinated chicken, cook on medium heat for 20 minutes.',
      'Add water as needed for gravy consistency. Serve with rice.',
    ],
    emoji: '🍗',
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala with Roti',
    description: 'Rich, creamy paneer in tomato-butter gravy with whole wheat roti.',
    cuisine: 'Indian',
    mealType: ['lunch', 'dinner'],
    calories: 520,
    protein: 24,
    carbs: 48,
    fat: 26,
    fiber: 4,
    prepTime: 15,
    cookTime: 25,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['vegetarian', 'high-protein', 'north-indian', 'rich'],
    ingredients: [
      { name: 'Paneer', quantity: '150g', category: 'Dairy' },
      { name: 'Whole wheat flour', quantity: '1 cup', category: 'Grains' },
      { name: 'Tomato', quantity: '3 medium', category: 'Produce' },
      { name: 'Butter', quantity: '1 tbsp', category: 'Dairy' },
      { name: 'Cream', quantity: '2 tbsp', category: 'Dairy' },
      { name: 'Cashews', quantity: '8-10', category: 'Nuts' },
      { name: 'Garam masala', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Kasuri methi', quantity: '1 tsp', category: 'Spices' },
    ],
    steps: [
      'Blanch and puree tomatoes with cashews for smooth gravy.',
      'Heat butter, add the tomato-cashew puree and cook 10 minutes.',
      'Add garam masala, kasuri methi, salt, and sugar.',
      'Add cubed paneer and cream. Simmer for 5 minutes.',
      'Knead dough for rotis, rest, roll, and cook on tawa.',
      'Serve paneer butter masala hot with fresh rotis.',
    ],
    emoji: '🧀',
  },
  {
    id: 'chole-bhature',
    name: 'Chole Bhature',
    description: 'Spicy chickpea curry served with deep-fried bread.',
    cuisine: 'Indian',
    mealType: ['lunch'],
    calories: 620,
    protein: 18,
    carbs: 72,
    fat: 28,
    fiber: 10,
    prepTime: 20,
    cookTime: 40,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['vegetarian', 'north-indian', 'indulgent', 'high-fiber'],
    ingredients: [
      { name: 'Chickpeas', quantity: '1/2 cup dried', category: 'Pulses' },
      { name: 'All-purpose flour', quantity: '1 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 large', category: 'Produce' },
      { name: 'Tomato', quantity: '2 medium', category: 'Produce' },
      { name: 'Chole masala', quantity: '1.5 tbsp', category: 'Spices' },
      { name: 'Tea bag', quantity: '1', category: 'Pantry' },
      { name: 'Oil for frying', quantity: 'for frying', category: 'Pantry' },
      { name: 'Yogurt', quantity: '2 tbsp', category: 'Dairy' },
    ],
    steps: [
      'Soak chickpeas overnight. Pressure cook with tea bag for dark color.',
      'Sauté onions until golden, add ginger-garlic paste.',
      'Add tomatoes and chole masala. Cook until oil separates.',
      'Add cooked chickpeas with water. Simmer 15 minutes.',
      'Knead bhature dough with flour, yogurt, and baking soda. Rest 2 hours.',
      'Roll and deep fry until puffed and golden.',
    ],
    emoji: '🫓',
  },
  {
    id: 'fish-curry-rice',
    name: 'Fish Curry with Rice',
    description: 'Coastal-style tangy fish curry with coconut and steamed rice.',
    cuisine: 'Indian',
    mealType: ['lunch', 'dinner'],
    calories: 480,
    protein: 32,
    carbs: 54,
    fat: 14,
    fiber: 3,
    prepTime: 10,
    cookTime: 20,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['non-veg', 'south-indian', 'coastal', 'omega-3'],
    ingredients: [
      { name: 'Fish fillets', quantity: '200g', category: 'Seafood' },
      { name: 'Basmati rice', quantity: '3/4 cup', category: 'Grains' },
      { name: 'Coconut milk', quantity: '1/2 cup', category: 'Pantry' },
      { name: 'Onion', quantity: '1 medium', category: 'Produce' },
      { name: 'Tomato', quantity: '1 medium', category: 'Produce' },
      { name: 'Tamarind paste', quantity: '1 tsp', category: 'Pantry' },
      { name: 'Fish curry powder', quantity: '1 tbsp', category: 'Spices' },
    ],
    steps: [
      'Marinate fish with turmeric and salt.',
      'Sauté onions, add tomato and curry powder.',
      'Add coconut milk and tamarind, bring to a simmer.',
      'Gently add fish pieces and cook 8-10 minutes.',
      'Serve with steamed rice.',
    ],
    emoji: '🐟',
  },
  // ========== INDIAN DINNER ==========
  {
    id: 'palak-dal-roti',
    name: 'Palak Dal with Roti',
    description: 'Spinach lentil curry – packed with iron and protein.',
    cuisine: 'Indian',
    mealType: ['dinner'],
    calories: 380,
    protein: 20,
    carbs: 52,
    fat: 8,
    fiber: 10,
    prepTime: 10,
    cookTime: 25,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'high-protein', 'high-fiber', 'iron-rich', 'healthy'],
    ingredients: [
      { name: 'Moong dal', quantity: '1/2 cup', category: 'Pulses' },
      { name: 'Spinach', quantity: '2 cups', category: 'Produce' },
      { name: 'Whole wheat flour', quantity: '1 cup', category: 'Grains' },
      { name: 'Garlic', quantity: '3 cloves', category: 'Produce' },
      { name: 'Cumin seeds', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Ghee', quantity: '1 tsp', category: 'Dairy' },
    ],
    steps: [
      'Cook moong dal until soft. Blanch and puree spinach.',
      'Mix spinach puree into cooked dal.',
      'Heat ghee, add cumin and sliced garlic.',
      'Pour tempering over the dal. Season to taste.',
      'Make soft rotis from whole wheat dough.',
      'Serve palak dal hot with fresh rotis.',
    ],
    emoji: '🥬',
  },
  {
    id: 'veg-biryani',
    name: 'Vegetable Biryani',
    description: 'Fragrant basmati rice layered with spiced mixed vegetables.',
    cuisine: 'Indian',
    mealType: ['lunch', 'dinner'],
    calories: 480,
    protein: 12,
    carbs: 68,
    fat: 16,
    fiber: 6,
    prepTime: 20,
    cookTime: 35,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['vegetarian', 'aromatic', 'festive'],
    ingredients: [
      { name: 'Basmati rice', quantity: '1 cup', category: 'Grains' },
      { name: 'Mixed vegetables', quantity: '1 cup', category: 'Produce' },
      { name: 'Onion', quantity: '2 medium', category: 'Produce' },
      { name: 'Yogurt', quantity: '3 tbsp', category: 'Dairy' },
      { name: 'Biryani masala', quantity: '1 tbsp', category: 'Spices' },
      { name: 'Saffron strands', quantity: 'a pinch', category: 'Spices' },
      { name: 'Ghee', quantity: '1 tbsp', category: 'Dairy' },
      { name: 'Mint leaves', quantity: '2 tbsp', category: 'Produce' },
    ],
    steps: [
      'Soak rice for 30 minutes. Parboil with whole spices.',
      'Sauté onions until golden. Add ginger-garlic paste.',
      'Add vegetables, biryani masala, yogurt, and cook 5 minutes.',
      'Layer parboiled rice over the vegetable mixture.',
      'Add saffron milk, mint, and fried onions on top.',
      'Seal pot with foil and cook on low heat 20 minutes (dum).',
    ],
    emoji: '🍚',
  },
  {
    id: 'grilled-chicken-salad',
    name: 'Tandoori Chicken Salad',
    description: 'Grilled tandoori chicken on a bed of fresh greens.',
    cuisine: 'Indian',
    mealType: ['lunch', 'dinner'],
    calories: 340,
    protein: 36,
    carbs: 12,
    fat: 16,
    fiber: 4,
    prepTime: 15,
    cookTime: 20,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['high-protein', 'low-carb', 'non-veg', 'healthy'],
    ingredients: [
      { name: 'Chicken breast', quantity: '200g', category: 'Meat' },
      { name: 'Yogurt', quantity: '3 tbsp', category: 'Dairy' },
      { name: 'Tandoori masala', quantity: '1 tbsp', category: 'Spices' },
      { name: 'Mixed greens', quantity: '2 cups', category: 'Produce' },
      { name: 'Cucumber', quantity: '1/2', category: 'Produce' },
      { name: 'Onion', quantity: '1/4', category: 'Produce' },
      { name: 'Lemon juice', quantity: '1 tbsp', category: 'Produce' },
    ],
    steps: [
      'Marinate chicken in yogurt and tandoori masala for 1 hour.',
      'Grill or bake at 200°C for 20 minutes until charred.',
      'Prepare salad with greens, cucumber, onion.',
      'Slice grilled chicken and arrange over salad.',
      'Drizzle with lemon juice and a pinch of chaat masala.',
    ],
    emoji: '🥗',
  },
  {
    id: 'egg-bhurji-roti',
    name: 'Egg Bhurji with Roti',
    description: 'Indian-style spiced scrambled eggs with whole wheat roti.',
    cuisine: 'Indian',
    mealType: ['breakfast', 'dinner'],
    calories: 380,
    protein: 22,
    carbs: 36,
    fat: 16,
    fiber: 4,
    prepTime: 5,
    cookTime: 10,
    difficulty: 'beginner',
    servings: 1,
    tags: ['high-protein', 'quick', 'non-veg'],
    ingredients: [
      { name: 'Eggs', quantity: '3', category: 'Dairy' },
      { name: 'Onion', quantity: '1 small', category: 'Produce' },
      { name: 'Tomato', quantity: '1 small', category: 'Produce' },
      { name: 'Green chili', quantity: '1', category: 'Produce' },
      { name: 'Whole wheat roti', quantity: '2', category: 'Grains' },
      { name: 'Oil', quantity: '1 tsp', category: 'Pantry' },
      { name: 'Turmeric', quantity: '1/4 tsp', category: 'Spices' },
    ],
    steps: [
      'Heat oil, sauté onions, tomato, and green chili.',
      'Beat eggs with turmeric and salt.',
      'Pour eggs into the pan and scramble on medium heat.',
      'Cook until eggs are set but still moist.',
      'Serve with warm rotis.',
    ],
    emoji: '🥚',
  },
  // ========== SNACKS ==========
  {
    id: 'sprout-chaat',
    name: 'Sprout Chaat',
    description: 'Tangy and crunchy mixed sprouts chaat with lime and chaat masala.',
    cuisine: 'Indian',
    mealType: ['snack'],
    calories: 180,
    protein: 12,
    carbs: 24,
    fat: 4,
    fiber: 8,
    prepTime: 10,
    cookTime: 0,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'high-protein', 'high-fiber', 'healthy', 'raw'],
    ingredients: [
      { name: 'Mixed sprouts', quantity: '1 cup', category: 'Pulses' },
      { name: 'Onion', quantity: '1/4 chopped', category: 'Produce' },
      { name: 'Tomato', quantity: '1/4 chopped', category: 'Produce' },
      { name: 'Lemon juice', quantity: '1 tbsp', category: 'Produce' },
      { name: 'Chaat masala', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Coriander', quantity: '1 tbsp', category: 'Produce' },
    ],
    steps: [
      'Steam or boil sprouts for 5 minutes if preferred, or use raw.',
      'Mix with onion, tomato, coriander.',
      'Add lemon juice, chaat masala, salt, and black pepper.',
      'Toss well and serve immediately.',
    ],
    emoji: '🌱',
  },
  {
    id: 'banana-peanut-butter',
    name: 'Banana with Peanut Butter',
    description: 'Simple, satisfying snack with natural energy.',
    cuisine: 'Global',
    mealType: ['snack'],
    calories: 240,
    protein: 8,
    carbs: 30,
    fat: 12,
    fiber: 4,
    prepTime: 2,
    cookTime: 0,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'quick', 'no-cook', 'energy'],
    ingredients: [
      { name: 'Banana', quantity: '1 medium', category: 'Produce' },
      { name: 'Peanut butter', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Slice banana.',
      'Spread peanut butter on slices or dip.',
    ],
    emoji: '🍌',
  },
  {
    id: 'roasted-makhana',
    name: 'Roasted Makhana',
    description: 'Crunchy roasted fox nuts – a guilt-free Indian snack.',
    cuisine: 'Indian',
    mealType: ['snack'],
    calories: 160,
    protein: 5,
    carbs: 22,
    fat: 6,
    fiber: 2,
    prepTime: 2,
    cookTime: 5,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'low-calorie', 'quick', 'indian'],
    ingredients: [
      { name: 'Makhana (fox nuts)', quantity: '1 cup', category: 'Pantry' },
      { name: 'Ghee', quantity: '1/2 tsp', category: 'Dairy' },
      { name: 'Black salt', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Black pepper', quantity: '1/4 tsp', category: 'Spices' },
    ],
    steps: [
      'Heat ghee in a pan on low heat.',
      'Add makhana and roast for 3-4 minutes until crunchy.',
      'Sprinkle salt and pepper. Toss well.',
      'Cool and store in an airtight container.',
    ],
    emoji: '🫧',
  },
  {
    id: 'fruit-yogurt',
    name: 'Fruit & Yogurt Bowl',
    description: 'Fresh seasonal fruits with creamy yogurt and honey.',
    cuisine: 'Global',
    mealType: ['snack', 'breakfast'],
    calories: 200,
    protein: 8,
    carbs: 32,
    fat: 5,
    fiber: 3,
    prepTime: 5,
    cookTime: 0,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'healthy', 'quick', 'no-cook'],
    ingredients: [
      { name: 'Greek yogurt', quantity: '3/4 cup', category: 'Dairy' },
      { name: 'Mixed fruits', quantity: '1/2 cup', category: 'Produce' },
      { name: 'Honey', quantity: '1 tsp', category: 'Pantry' },
      { name: 'Chia seeds', quantity: '1 tsp', category: 'Pantry' },
    ],
    steps: [
      'Add yogurt to a bowl.',
      'Top with chopped fruits and chia seeds.',
      'Drizzle honey and serve.',
    ],
    emoji: '🍓',
  },
  // ========== GLOBAL MEALS ==========
  {
    id: 'oatmeal-banana',
    name: 'Oatmeal with Banana & Almonds',
    description: 'Warm, comforting oatmeal topped with banana and almonds.',
    cuisine: 'Global',
    mealType: ['breakfast'],
    calories: 320,
    protein: 10,
    carbs: 50,
    fat: 10,
    fiber: 6,
    prepTime: 5,
    cookTime: 5,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'high-fiber', 'quick', 'healthy'],
    ingredients: [
      { name: 'Rolled oats', quantity: '1/2 cup', category: 'Grains' },
      { name: 'Milk', quantity: '1 cup', category: 'Dairy' },
      { name: 'Banana', quantity: '1 small', category: 'Produce' },
      { name: 'Almonds', quantity: '8-10', category: 'Nuts' },
      { name: 'Honey', quantity: '1 tsp', category: 'Pantry' },
    ],
    steps: [
      'Cook oats with milk on medium heat for 3-4 minutes.',
      'Transfer to a bowl.',
      'Top with sliced banana, chopped almonds, and honey.',
    ],
    emoji: '🥣',
  },
  {
    id: 'grilled-sandwich',
    name: 'Grilled Veggie Sandwich',
    description: 'Whole wheat grilled sandwich loaded with vegetables.',
    cuisine: 'Global',
    mealType: ['breakfast', 'lunch', 'snack'],
    calories: 320,
    protein: 12,
    carbs: 42,
    fat: 12,
    fiber: 5,
    prepTime: 10,
    cookTime: 5,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'quick'],
    ingredients: [
      { name: 'Whole wheat bread', quantity: '2 slices', category: 'Grains' },
      { name: 'Onion', quantity: '3-4 rings', category: 'Produce' },
      { name: 'Tomato', quantity: '3-4 slices', category: 'Produce' },
      { name: 'Cucumber', quantity: '4 slices', category: 'Produce' },
      { name: 'Cheese slice', quantity: '1', category: 'Dairy' },
      { name: 'Green chutney', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Butter', quantity: '1 tsp', category: 'Dairy' },
    ],
    steps: [
      'Spread green chutney on both bread slices.',
      'Layer vegetables and cheese.',
      'Butter the outside and grill until golden and crispy.',
      'Cut diagonally and serve hot.',
    ],
    emoji: '🥪',
  },
  {
    id: 'pasta-marinara',
    name: 'Whole Wheat Pasta Marinara',
    description: 'Whole wheat pasta with homemade marinara sauce.',
    cuisine: 'Italian',
    mealType: ['lunch', 'dinner'],
    calories: 420,
    protein: 14,
    carbs: 62,
    fat: 12,
    fiber: 8,
    prepTime: 10,
    cookTime: 20,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'italian', 'comfort-food'],
    ingredients: [
      { name: 'Whole wheat pasta', quantity: '80g', category: 'Grains' },
      { name: 'Tomatoes', quantity: '3 medium', category: 'Produce' },
      { name: 'Garlic', quantity: '3 cloves', category: 'Produce' },
      { name: 'Olive oil', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Basil', quantity: '5-6 leaves', category: 'Produce' },
      { name: 'Parmesan', quantity: '1 tbsp grated', category: 'Dairy' },
    ],
    steps: [
      'Cook pasta in salted boiling water per package instructions.',
      'Sauté garlic in olive oil until fragrant.',
      'Add chopped tomatoes, salt, and pepper. Cook 10 minutes.',
      'Toss pasta with marinara sauce.',
      'Top with fresh basil and parmesan.',
    ],
    emoji: '🍝',
  },
  {
    id: 'stir-fry-tofu',
    name: 'Tofu Vegetable Stir-Fry',
    description: 'High-protein tofu stir-fried with colorful vegetables.',
    cuisine: 'Asian',
    mealType: ['lunch', 'dinner'],
    calories: 340,
    protein: 22,
    carbs: 28,
    fat: 16,
    fiber: 5,
    prepTime: 10,
    cookTime: 15,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegan', 'high-protein', 'low-carb', 'healthy'],
    ingredients: [
      { name: 'Firm tofu', quantity: '150g', category: 'Protein' },
      { name: 'Bell peppers', quantity: '1/2 cup sliced', category: 'Produce' },
      { name: 'Broccoli', quantity: '1/2 cup', category: 'Produce' },
      { name: 'Soy sauce', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Sesame oil', quantity: '1 tsp', category: 'Pantry' },
      { name: 'Garlic', quantity: '2 cloves', category: 'Produce' },
      { name: 'Ginger', quantity: '1/2 inch', category: 'Produce' },
    ],
    steps: [
      'Press and cube tofu. Pan-fry until golden on all sides.',
      'Remove tofu. Stir-fry garlic and ginger.',
      'Add vegetables and cook 3-4 minutes.',
      'Add soy sauce and return tofu.',
      'Toss well and drizzle with sesame oil.',
    ],
    emoji: '🥘',
  },
  {
    id: 'chicken-wrap',
    name: 'Chicken Tikka Wrap',
    description: 'Grilled chicken tikka in a whole wheat wrap with veggies.',
    cuisine: 'Indian',
    mealType: ['lunch', 'snack'],
    calories: 380,
    protein: 30,
    carbs: 34,
    fat: 14,
    fiber: 4,
    prepTime: 15,
    cookTime: 15,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['high-protein', 'non-veg', 'indian'],
    ingredients: [
      { name: 'Chicken breast', quantity: '150g', category: 'Meat' },
      { name: 'Whole wheat tortilla', quantity: '1', category: 'Grains' },
      { name: 'Yogurt', quantity: '2 tbsp', category: 'Dairy' },
      { name: 'Tikka masala', quantity: '1 tbsp', category: 'Spices' },
      { name: 'Lettuce', quantity: '2 leaves', category: 'Produce' },
      { name: 'Onion', quantity: '2 rings', category: 'Produce' },
      { name: 'Mint chutney', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Marinate chicken in yogurt and tikka masala for 30 minutes.',
      'Grill or pan-fry until fully cooked.',
      'Warm the tortilla on a tawa.',
      'Spread mint chutney, add lettuce, onion, and sliced chicken.',
      'Roll tightly and slice diagonally.',
    ],
    emoji: '🌯',
  },
  {
    id: 'dosa-chutney',
    name: 'Masala Dosa',
    description: 'Crispy rice crepe filled with spiced potato filling.',
    cuisine: 'Indian',
    mealType: ['breakfast', 'dinner'],
    calories: 370,
    protein: 8,
    carbs: 56,
    fat: 12,
    fiber: 4,
    prepTime: 10,
    cookTime: 15,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['vegetarian', 'south-indian', 'classic'],
    ingredients: [
      { name: 'Dosa batter', quantity: '1 cup', category: 'Grains' },
      { name: 'Potato', quantity: '2 medium boiled', category: 'Produce' },
      { name: 'Onion', quantity: '1 medium', category: 'Produce' },
      { name: 'Mustard seeds', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Turmeric', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Curry leaves', quantity: '5-6', category: 'Produce' },
      { name: 'Oil', quantity: '1 tsp', category: 'Pantry' },
    ],
    steps: [
      'Prepare potato filling: sauté mustard seeds, curry leaves, onion.',
      'Add turmeric and mashed potatoes. Mix well.',
      'Heat a non-stick tawa, pour batter and spread thin.',
      'Drizzle oil around edges. Cook until crispy.',
      'Place potato filling on one side and fold.',
      'Serve with coconut chutney and sambar.',
    ],
    emoji: '🫓',
  },
  {
    id: 'khichdi',
    name: 'Moong Dal Khichdi',
    description: 'Comforting one-pot rice and lentil dish – easy to digest.',
    cuisine: 'Indian',
    mealType: ['dinner'],
    calories: 350,
    protein: 14,
    carbs: 58,
    fat: 6,
    fiber: 6,
    prepTime: 5,
    cookTime: 20,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'comfort-food', 'easy-digest', 'one-pot'],
    ingredients: [
      { name: 'Rice', quantity: '1/2 cup', category: 'Grains' },
      { name: 'Moong dal', quantity: '1/4 cup', category: 'Pulses' },
      { name: 'Ghee', quantity: '1 tsp', category: 'Dairy' },
      { name: 'Cumin seeds', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Turmeric', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Water', quantity: '2.5 cups', category: 'Pantry' },
    ],
    steps: [
      'Wash rice and dal together.',
      'Pressure cook with water, turmeric, and salt for 3 whistles.',
      'Heat ghee, add cumin seeds.',
      'Pour tempering over khichdi and mix gently.',
      'Serve hot with pickle or papad.',
    ],
    tips: 'Add mixed vegetables for a more nutritious version.',
    emoji: '🍲',
  },
  {
    id: 'smoothie-bowl',
    name: 'Mixed Berry Smoothie Bowl',
    description: 'Thick blended smoothie topped with granola and fruits.',
    cuisine: 'Global',
    mealType: ['breakfast', 'snack'],
    calories: 280,
    protein: 10,
    carbs: 42,
    fat: 8,
    fiber: 6,
    prepTime: 5,
    cookTime: 0,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'healthy', 'no-cook', 'quick'],
    ingredients: [
      { name: 'Frozen berries', quantity: '1 cup', category: 'Produce' },
      { name: 'Banana', quantity: '1/2', category: 'Produce' },
      { name: 'Yogurt', quantity: '1/2 cup', category: 'Dairy' },
      { name: 'Granola', quantity: '2 tbsp', category: 'Pantry' },
      { name: 'Honey', quantity: '1 tsp', category: 'Pantry' },
    ],
    steps: [
      'Blend frozen berries, banana, and yogurt until thick.',
      'Pour into a bowl.',
      'Top with granola, sliced fruit, and drizzle honey.',
    ],
    emoji: '🫐',
  },
  // ========== MORE VARIETY ==========
  {
    id: 'roti-sabzi',
    name: 'Mixed Vegetable Sabzi with Roti',
    description: 'Dry mixed vegetable curry with fresh whole wheat rotis.',
    cuisine: 'Indian',
    mealType: ['lunch', 'dinner'],
    calories: 360,
    protein: 10,
    carbs: 52,
    fat: 12,
    fiber: 8,
    prepTime: 10,
    cookTime: 20,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'healthy', 'north-indian'],
    ingredients: [
      { name: 'Mixed vegetables', quantity: '1.5 cups', category: 'Produce' },
      { name: 'Whole wheat flour', quantity: '1 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 medium', category: 'Produce' },
      { name: 'Tomato', quantity: '1', category: 'Produce' },
      { name: 'Garam masala', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Turmeric', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Chop all vegetables into small cubes.',
      'Sauté onions, add turmeric and tomato.',
      'Add vegetables with a splash of water. Cook covered 10 minutes.',
      'Add garam masala and salt. Cook until dry.',
      'Prepare rotis and serve hot.',
    ],
    emoji: '🥘',
  },
  {
    id: 'greek-salad',
    name: 'Greek Salad with Quinoa',
    description: 'Mediterranean salad with quinoa for extra protein.',
    cuisine: 'Mediterranean',
    mealType: ['lunch'],
    calories: 340,
    protein: 12,
    carbs: 38,
    fat: 16,
    fiber: 6,
    prepTime: 10,
    cookTime: 15,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'mediterranean', 'healthy', 'high-fiber'],
    ingredients: [
      { name: 'Quinoa', quantity: '1/3 cup', category: 'Grains' },
      { name: 'Cucumber', quantity: '1/2', category: 'Produce' },
      { name: 'Cherry tomatoes', quantity: '6', category: 'Produce' },
      { name: 'Feta cheese', quantity: '30g', category: 'Dairy' },
      { name: 'Olives', quantity: '6', category: 'Pantry' },
      { name: 'Olive oil', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Lemon juice', quantity: '1 tbsp', category: 'Produce' },
    ],
    steps: [
      'Cook quinoa per package directions. Cool.',
      'Chop cucumber, halve tomatoes.',
      'Combine quinoa, vegetables, olives, and crumbled feta.',
      'Dress with olive oil, lemon juice, salt, and oregano.',
    ],
    emoji: '🥗',
  },
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    description: 'Grilled spiced paneer and vegetable skewers.',
    cuisine: 'Indian',
    mealType: ['snack', 'dinner'],
    calories: 280,
    protein: 18,
    carbs: 12,
    fat: 18,
    fiber: 2,
    prepTime: 15,
    cookTime: 15,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['vegetarian', 'high-protein', 'low-carb', 'indian'],
    ingredients: [
      { name: 'Paneer', quantity: '150g', category: 'Dairy' },
      { name: 'Bell peppers', quantity: '1/2 cup', category: 'Produce' },
      { name: 'Onion', quantity: '1/2', category: 'Produce' },
      { name: 'Yogurt', quantity: '3 tbsp', category: 'Dairy' },
      { name: 'Tikka masala', quantity: '1 tbsp', category: 'Spices' },
      { name: 'Lemon juice', quantity: '1 tbsp', category: 'Produce' },
    ],
    steps: [
      'Cube paneer and vegetables into chunks.',
      'Mix yogurt, tikka masala, lemon juice, and salt.',
      'Marinate paneer and vegetables for 30 minutes.',
      'Thread onto skewers.',
      'Grill or bake at 200°C for 12-15 minutes.',
      'Serve with mint chutney.',
    ],
    emoji: '🧀',
  },
  {
    id: 'dal-fry',
    name: 'Dal Fry with Jeera Rice',
    description: 'Hearty spiced lentils with fragrant cumin rice.',
    cuisine: 'Indian',
    mealType: ['lunch', 'dinner'],
    calories: 440,
    protein: 16,
    carbs: 66,
    fat: 10,
    fiber: 8,
    prepTime: 10,
    cookTime: 25,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'comfort-food', 'indian'],
    ingredients: [
      { name: 'Toor dal', quantity: '1/2 cup', category: 'Pulses' },
      { name: 'Basmati rice', quantity: '3/4 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 medium', category: 'Produce' },
      { name: 'Tomato', quantity: '1 medium', category: 'Produce' },
      { name: 'Cumin seeds', quantity: '1 tsp', category: 'Spices' },
      { name: 'Garlic', quantity: '3 cloves', category: 'Produce' },
      { name: 'Butter', quantity: '1 tbsp', category: 'Dairy' },
    ],
    steps: [
      'Cook toor dal until very soft.',
      'Sauté cumin in butter, add garlic and onions.',
      'Add tomatoes, chili powder, and cook until soft.',
      'Mix in cooked dal and simmer.',
      'Cook jeera rice with cumin seeds.',
      'Serve dal fry hot over jeera rice.',
    ],
    emoji: '🍛',
  },
  {
    id: 'overnight-oats',
    name: 'Overnight Oats',
    description: 'No-cook oats soaked overnight with chia and fruit.',
    cuisine: 'Global',
    mealType: ['breakfast'],
    calories: 300,
    protein: 10,
    carbs: 44,
    fat: 10,
    fiber: 7,
    prepTime: 5,
    cookTime: 0,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'no-cook', 'meal-prep', 'healthy'],
    ingredients: [
      { name: 'Rolled oats', quantity: '1/2 cup', category: 'Grains' },
      { name: 'Milk', quantity: '1/2 cup', category: 'Dairy' },
      { name: 'Yogurt', quantity: '1/4 cup', category: 'Dairy' },
      { name: 'Chia seeds', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Honey', quantity: '1 tsp', category: 'Pantry' },
      { name: 'Mixed berries', quantity: '1/4 cup', category: 'Produce' },
    ],
    steps: [
      'Mix oats, milk, yogurt, chia seeds, and honey in a jar.',
      'Refrigerate overnight.',
      'In the morning, top with fresh berries.',
      'Enjoy cold or at room temperature.',
    ],
    emoji: '🫙',
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi with Roti',
    description: 'Classic potato-cauliflower dry curry with whole wheat rotis.',
    cuisine: 'Indian',
    mealType: ['lunch', 'dinner'],
    calories: 390,
    protein: 10,
    carbs: 56,
    fat: 14,
    fiber: 6,
    prepTime: 10,
    cookTime: 20,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'north-indian', 'classic'],
    ingredients: [
      { name: 'Potato', quantity: '1 large', category: 'Produce' },
      { name: 'Cauliflower', quantity: '1 cup florets', category: 'Produce' },
      { name: 'Whole wheat flour', quantity: '1 cup', category: 'Grains' },
      { name: 'Cumin seeds', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Turmeric', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Garam masala', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Cut potato and cauliflower into bite-sized pieces.',
      'Heat oil, add cumin seeds.',
      'Add potatoes first, cook 5 minutes. Add cauliflower.',
      'Add spices and salt. Cook covered on low heat 12-15 minutes.',
      'Prepare rotis and serve together.',
    ],
    emoji: '🥔',
  },
  {
    id: 'protein-shake',
    name: 'Banana Protein Shake',
    description: 'Quick post-workout protein shake.',
    cuisine: 'Global',
    mealType: ['snack', 'breakfast'],
    calories: 260,
    protein: 24,
    carbs: 30,
    fat: 6,
    fiber: 3,
    prepTime: 3,
    cookTime: 0,
    difficulty: 'beginner',
    servings: 1,
    tags: ['high-protein', 'quick', 'post-workout'],
    ingredients: [
      { name: 'Protein powder', quantity: '1 scoop', category: 'Pantry' },
      { name: 'Banana', quantity: '1 medium', category: 'Produce' },
      { name: 'Milk', quantity: '1 cup', category: 'Dairy' },
      { name: 'Peanut butter', quantity: '1/2 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Add all ingredients to a blender.',
      'Blend until smooth.',
      'Pour and enjoy immediately.',
    ],
    emoji: '🥤',
  },
  {
    id: 'egg-fried-rice',
    name: 'Egg Fried Rice',
    description: 'Quick Indo-Chinese style egg fried rice.',
    cuisine: 'Asian',
    mealType: ['lunch', 'dinner'],
    calories: 420,
    protein: 16,
    carbs: 56,
    fat: 14,
    fiber: 3,
    prepTime: 10,
    cookTime: 10,
    difficulty: 'beginner',
    servings: 1,
    tags: ['non-veg', 'quick', 'indo-chinese'],
    ingredients: [
      { name: 'Cooked rice', quantity: '1.5 cups', category: 'Grains' },
      { name: 'Eggs', quantity: '2', category: 'Dairy' },
      { name: 'Spring onions', quantity: '2', category: 'Produce' },
      { name: 'Carrot', quantity: '1/4 cup diced', category: 'Produce' },
      { name: 'Soy sauce', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Heat oil, scramble eggs and set aside.',
      'Stir-fry vegetables on high heat.',
      'Add cold leftover rice and soy sauce.',
      'Toss everything with scrambled eggs.',
      'Garnish with spring onion greens.',
    ],
    tips: 'Use day-old cold rice for the best texture.',
    emoji: '🍳',
  },
  {
    id: 'chana-salad',
    name: 'Chickpea Salad',
    description: 'Protein-rich chickpea salad with cucumber and lemon dressing.',
    cuisine: 'Global',
    mealType: ['lunch', 'snack'],
    calories: 280,
    protein: 14,
    carbs: 36,
    fat: 10,
    fiber: 10,
    prepTime: 10,
    cookTime: 0,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'vegan', 'high-fiber', 'high-protein', 'no-cook'],
    ingredients: [
      { name: 'Boiled chickpeas', quantity: '1 cup', category: 'Pulses' },
      { name: 'Cucumber', quantity: '1/2', category: 'Produce' },
      { name: 'Tomato', quantity: '1 small', category: 'Produce' },
      { name: 'Red onion', quantity: '1/4', category: 'Produce' },
      { name: 'Olive oil', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Lemon juice', quantity: '1 tbsp', category: 'Produce' },
    ],
    steps: [
      'Combine chickpeas, diced cucumber, tomato, and onion.',
      'Dress with olive oil, lemon juice, salt, and pepper.',
      'Add cumin powder and chaat masala for Indian twist.',
      'Toss well and serve.',
    ],
    emoji: '🥗',
  },
  {
    id: 'butter-chicken',
    name: 'Butter Chicken with Naan',
    description: 'Creamy tomato-based chicken curry with soft naan bread.',
    cuisine: 'Indian',
    mealType: ['dinner'],
    calories: 580,
    protein: 36,
    carbs: 46,
    fat: 26,
    fiber: 3,
    prepTime: 20,
    cookTime: 30,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['non-veg', 'north-indian', 'rich', 'popular'],
    ingredients: [
      { name: 'Chicken', quantity: '200g', category: 'Meat' },
      { name: 'Naan', quantity: '2', category: 'Grains' },
      { name: 'Tomato puree', quantity: '1 cup', category: 'Produce' },
      { name: 'Butter', quantity: '2 tbsp', category: 'Dairy' },
      { name: 'Cream', quantity: '3 tbsp', category: 'Dairy' },
      { name: 'Cashews', quantity: '10', category: 'Nuts' },
      { name: 'Garam masala', quantity: '1 tsp', category: 'Spices' },
      { name: 'Yogurt', quantity: '3 tbsp', category: 'Dairy' },
    ],
    steps: [
      'Marinate chicken in yogurt and spices for 1 hour.',
      'Grill or pan-fry chicken until charred.',
      'Melt butter, add tomato puree and cashew paste.',
      'Cook 10 minutes, add garam masala and cream.',
      'Add grilled chicken and simmer 5 minutes.',
      'Serve with warm naan.',
    ],
    emoji: '🍗',
  },
  // ========== ADDITIONAL DINNER RECIPES ==========
  {
    id: 'mushroom-masala',
    name: 'Mushroom Masala with Rice',
    description: 'Spiced mushroom curry in onion-tomato gravy with steamed rice.',
    cuisine: 'Indian',
    mealType: ['dinner'],
    calories: 380,
    protein: 12,
    carbs: 54,
    fat: 12,
    fiber: 5,
    prepTime: 10,
    cookTime: 20,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'healthy', 'indian'],
    ingredients: [
      { name: 'Mushrooms', quantity: '200g', category: 'Produce' },
      { name: 'Basmati rice', quantity: '3/4 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 large', category: 'Produce' },
      { name: 'Tomato', quantity: '2 medium', category: 'Produce' },
      { name: 'Ginger-garlic paste', quantity: '1 tbsp', category: 'Produce' },
      { name: 'Garam masala', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Slice mushrooms. Sauté onions until golden.',
      'Add ginger-garlic paste, cook 1 minute.',
      'Add tomatoes and spices, cook until soft.',
      'Add mushrooms, cook 8-10 minutes.',
      'Serve with steamed basmati rice.',
    ],
    emoji: '🍄',
  },
  {
    id: 'methi-thepla',
    name: 'Methi Thepla with Raita',
    description: 'Fenugreek-spiced flatbread served with cool cucumber raita.',
    cuisine: 'Indian',
    mealType: ['dinner'],
    calories: 340,
    protein: 12,
    carbs: 48,
    fat: 10,
    fiber: 6,
    prepTime: 15,
    cookTime: 15,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'healthy', 'gujarati', 'indian'],
    ingredients: [
      { name: 'Whole wheat flour', quantity: '1 cup', category: 'Grains' },
      { name: 'Fresh methi leaves', quantity: '1 cup', category: 'Produce' },
      { name: 'Yogurt', quantity: '2 tbsp', category: 'Dairy' },
      { name: 'Cucumber', quantity: '1/2', category: 'Produce' },
      { name: 'Cumin powder', quantity: '1/2 tsp', category: 'Spices' },
      { name: 'Oil', quantity: '1 tsp', category: 'Pantry' },
    ],
    steps: [
      'Mix flour, chopped methi, yogurt, turmeric, and salt into dough.',
      'Rest 10 minutes. Roll into thin rounds.',
      'Cook on hot tawa with oil until golden on both sides.',
      'Grate cucumber into yogurt with cumin and salt for raita.',
      'Serve theplas hot with cucumber raita.',
    ],
    emoji: '🫓',
  },
  {
    id: 'kadhi-chawal',
    name: 'Kadhi Chawal',
    description: 'Tangy yogurt-based curry with besan pakodas and steamed rice.',
    cuisine: 'Indian',
    mealType: ['dinner'],
    calories: 420,
    protein: 14,
    carbs: 60,
    fat: 14,
    fiber: 4,
    prepTime: 15,
    cookTime: 25,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['vegetarian', 'north-indian', 'comfort-food'],
    ingredients: [
      { name: 'Yogurt', quantity: '1 cup', category: 'Dairy' },
      { name: 'Besan (gram flour)', quantity: '3 tbsp', category: 'Grains' },
      { name: 'Basmati rice', quantity: '3/4 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 small', category: 'Produce' },
      { name: 'Fenugreek seeds', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Turmeric', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Whisk yogurt with besan, turmeric, and water until smooth.',
      'Make small besan pakodas and fry until golden.',
      'Heat oil, add fenugreek seeds and curry leaves.',
      'Pour in the yogurt mixture and simmer 15-20 minutes.',
      'Add pakodas and cook 5 more minutes. Serve with rice.',
    ],
    emoji: '🍛',
  },
  {
    id: 'baingan-bharta',
    name: 'Baingan Bharta with Roti',
    description: 'Smoky roasted eggplant mash with fresh rotis.',
    cuisine: 'Indian',
    mealType: ['dinner'],
    calories: 350,
    protein: 10,
    carbs: 50,
    fat: 12,
    fiber: 8,
    prepTime: 10,
    cookTime: 25,
    difficulty: 'intermediate',
    servings: 1,
    tags: ['vegetarian', 'north-indian', 'healthy'],
    ingredients: [
      { name: 'Eggplant', quantity: '1 large', category: 'Produce' },
      { name: 'Whole wheat flour', quantity: '1 cup', category: 'Grains' },
      { name: 'Onion', quantity: '1 medium', category: 'Produce' },
      { name: 'Tomato', quantity: '1 medium', category: 'Produce' },
      { name: 'Green peas', quantity: '1/4 cup', category: 'Produce' },
      { name: 'Oil', quantity: '1 tbsp', category: 'Pantry' },
    ],
    steps: [
      'Roast whole eggplant on open flame until skin is charred.',
      'Peel skin and mash the pulp.',
      'Sauté onions, add tomatoes and peas.',
      'Add mashed eggplant and spices. Cook 5 minutes.',
      'Make rotis and serve with bharta.',
    ],
    emoji: '🍆',
  },
  {
    id: 'curd-rice',
    name: 'Curd Rice (Thayir Sadam)',
    description: 'Cooling South Indian yogurt rice – perfect for a light dinner.',
    cuisine: 'Indian',
    mealType: ['dinner'],
    calories: 300,
    protein: 10,
    carbs: 48,
    fat: 6,
    fiber: 2,
    prepTime: 5,
    cookTime: 15,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegetarian', 'south-indian', 'light', 'probiotic'],
    ingredients: [
      { name: 'Cooked rice', quantity: '1 cup', category: 'Grains' },
      { name: 'Yogurt', quantity: '1 cup', category: 'Dairy' },
      { name: 'Milk', quantity: '1/4 cup', category: 'Dairy' },
      { name: 'Mustard seeds', quantity: '1/4 tsp', category: 'Spices' },
      { name: 'Curry leaves', quantity: '5', category: 'Produce' },
      { name: 'Pomegranate', quantity: '2 tbsp', category: 'Produce' },
    ],
    steps: [
      'Mix cooked rice with yogurt and milk. Mash slightly.',
      'Heat oil, add mustard seeds and curry leaves.',
      'Pour tempering over curd rice. Mix well.',
      'Garnish with pomegranate and coriander.',
      'Serve at room temperature or chilled.',
    ],
    emoji: '🍚',
  },
  {
    id: 'grilled-fish-veggies',
    name: 'Grilled Fish with Steamed Vegetables',
    description: 'Lightly spiced grilled fish fillet with seasonal steamed vegetables.',
    cuisine: 'Global',
    mealType: ['dinner'],
    calories: 320,
    protein: 34,
    carbs: 18,
    fat: 12,
    fiber: 5,
    prepTime: 10,
    cookTime: 15,
    difficulty: 'beginner',
    servings: 1,
    tags: ['non-veg', 'high-protein', 'low-carb', 'healthy', 'omega-3'],
    ingredients: [
      { name: 'Fish fillet', quantity: '200g', category: 'Seafood' },
      { name: 'Broccoli', quantity: '1/2 cup', category: 'Produce' },
      { name: 'Carrots', quantity: '1/2 cup', category: 'Produce' },
      { name: 'Lemon', quantity: '1/2', category: 'Produce' },
      { name: 'Olive oil', quantity: '1 tbsp', category: 'Pantry' },
      { name: 'Garlic', quantity: '2 cloves', category: 'Produce' },
    ],
    steps: [
      'Marinate fish with lemon juice, garlic, olive oil, and herbs.',
      'Steam broccoli and carrots until tender-crisp.',
      'Grill or pan-sear fish 4-5 minutes per side.',
      'Season steamed vegetables with salt and pepper.',
      'Serve fish over vegetables with lemon wedge.',
    ],
    emoji: '🐟',
  },
  {
    id: 'tofu-curry-rice',
    name: 'Tofu Curry with Brown Rice',
    description: 'Protein-packed tofu in a mildly spiced coconut curry.',
    cuisine: 'Asian',
    mealType: ['dinner'],
    calories: 400,
    protein: 20,
    carbs: 50,
    fat: 14,
    fiber: 6,
    prepTime: 10,
    cookTime: 20,
    difficulty: 'beginner',
    servings: 1,
    tags: ['vegan', 'high-protein', 'healthy'],
    ingredients: [
      { name: 'Firm tofu', quantity: '150g', category: 'Produce' },
      { name: 'Brown rice', quantity: '3/4 cup', category: 'Grains' },
      { name: 'Coconut milk', quantity: '1/2 cup', category: 'Pantry' },
      { name: 'Bell pepper', quantity: '1/2', category: 'Produce' },
      { name: 'Onion', quantity: '1 medium', category: 'Produce' },
      { name: 'Curry powder', quantity: '1 tbsp', category: 'Spices' },
      { name: 'Oil', quantity: '1 tsp', category: 'Pantry' },
    ],
    steps: [
      'Press and cube tofu. Pan-fry until golden.',
      'Sauté onions and bell pepper.',
      'Add curry powder and coconut milk. Simmer 10 minutes.',
      'Add tofu and cook 5 more minutes.',
      'Serve over cooked brown rice.',
    ],
    emoji: '🥘',
  },
  // ========== EXPANDED RECIPES (60 new) ==========
  // ── BREAKFAST (15) ──
  { id: 'moong-dal-chilla', name: 'Moong Dal Chilla', description: 'Protein-rich lentil crepes with green chutney.', cuisine: 'Indian', mealType: ['breakfast'], calories: 220, protein: 14, carbs: 28, fat: 6, fiber: 5, prepTime: 10, cookTime: 10, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'high-protein', 'budget'], ingredients: [{ name: 'Moong dal', quantity: '1/2 cup', category: 'Pulses' }, { name: 'Onion', quantity: '1 small', category: 'Produce' }, { name: 'Green chilli', quantity: '1', category: 'Produce' }], steps: ['Soak and grind moong dal.', 'Add spices, spread on pan.', 'Cook both sides until golden.'], emoji: '🫓', volumeFactor: 3, suitableFor: ['diabetes', 'weight_loss'], avoidFor: [] },
  { id: 'ragi-porridge', name: 'Ragi Porridge', description: 'Calcium-rich finger millet porridge with jaggery.', cuisine: 'Indian', mealType: ['breakfast'], calories: 200, protein: 6, carbs: 40, fat: 2, fiber: 4, prepTime: 5, cookTime: 10, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'budget', 'gluten-free'], ingredients: [{ name: 'Ragi flour', quantity: '3 tbsp', category: 'Grains' }, { name: 'Milk', quantity: '1 cup', category: 'Dairy' }, { name: 'Jaggery', quantity: '1 tbsp', category: 'Pantry' }], steps: ['Mix ragi flour with water.', 'Add to boiling milk, stir.', 'Cook 5 min, add jaggery.'], emoji: '🥣', volumeFactor: 4, suitableFor: ['weight_loss'], avoidFor: [] },
  { id: 'anda-bhurji', name: 'Anda Bhurji with Toast', description: 'Spicy scrambled eggs with buttered toast.', cuisine: 'Indian', mealType: ['breakfast'], calories: 310, protein: 18, carbs: 25, fat: 16, fiber: 2, prepTime: 5, cookTime: 8, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'high-protein'], ingredients: [{ name: 'Eggs', quantity: '3', category: 'Dairy' }, { name: 'Bread', quantity: '2 slices', category: 'Grains' }, { name: 'Onion', quantity: '1 small', category: 'Produce' }, { name: 'Butter', quantity: '1 tsp', category: 'Dairy' }], steps: ['Sauté onion and chillies.', 'Add beaten eggs, scramble.', 'Serve with buttered toast.'], emoji: '🍳', volumeFactor: 2, suitableFor: [], avoidFor: ['cholesterol'] },
  { id: 'overnight-oats', name: 'Overnight Oats with Banana', description: 'No-cook oats soaked overnight with fruits.', cuisine: 'Global', mealType: ['breakfast'], calories: 280, protein: 10, carbs: 45, fat: 7, fiber: 6, prepTime: 5, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'high-fiber', 'no-cook'], ingredients: [{ name: 'Oats', quantity: '1/2 cup', category: 'Grains' }, { name: 'Milk', quantity: '3/4 cup', category: 'Dairy' }, { name: 'Banana', quantity: '1', category: 'Produce' }, { name: 'Honey', quantity: '1 tsp', category: 'Pantry' }], steps: ['Mix oats with milk and honey.', 'Refrigerate overnight.', 'Top with banana slices.'], emoji: '🥣', volumeFactor: 3, suitableFor: ['weight_loss', 'diabetes'], avoidFor: [] },
  { id: 'pesarattu', name: 'Pesarattu (Green Gram Dosa)', description: 'Andhra-style protein-packed green gram dosa.', cuisine: 'Indian', mealType: ['breakfast'], calories: 240, protein: 12, carbs: 35, fat: 5, fiber: 6, prepTime: 15, cookTime: 10, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'high-protein', 'south-indian'], ingredients: [{ name: 'Green gram', quantity: '1 cup', category: 'Pulses' }, { name: 'Rice', quantity: '2 tbsp', category: 'Grains' }, { name: 'Ginger', quantity: '1 inch', category: 'Produce' }], steps: ['Soak and grind green gram with rice.', 'Spread thin on tawa.', 'Cook until crispy, serve with chutney.'], emoji: '🫓', volumeFactor: 3, suitableFor: ['diabetes', 'weight_loss'], avoidFor: [] },
  { id: 'avocado-toast', name: 'Avocado Toast with Egg', description: 'Multigrain toast with smashed avocado and poached egg.', cuisine: 'Global', mealType: ['breakfast'], calories: 350, protein: 14, carbs: 30, fat: 20, fiber: 7, prepTime: 5, cookTime: 5, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'healthy-fats'], ingredients: [{ name: 'Avocado', quantity: '1/2', category: 'Produce' }, { name: 'Multigrain bread', quantity: '2 slices', category: 'Grains' }, { name: 'Egg', quantity: '1', category: 'Dairy' }], steps: ['Toast bread.', 'Mash avocado with salt, lemon.', 'Top with poached egg.'], emoji: '🥑', volumeFactor: 2, suitableFor: [], avoidFor: [] },
  { id: 'besan-chilla', name: 'Besan Chilla', description: 'Quick gram flour pancakes with vegetables.', cuisine: 'Indian', mealType: ['breakfast'], calories: 190, protein: 10, carbs: 22, fat: 7, fiber: 4, prepTime: 5, cookTime: 8, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'budget', 'quick'], ingredients: [{ name: 'Besan', quantity: '1/2 cup', category: 'Grains' }, { name: 'Onion', quantity: '1 small', category: 'Produce' }, { name: 'Tomato', quantity: '1 small', category: 'Produce' }], steps: ['Mix besan with water and spices.', 'Add chopped veggies.', 'Cook like a pancake.'], emoji: '🥞', volumeFactor: 3, suitableFor: ['diabetes', 'weight_loss'], avoidFor: [] },
  { id: 'sabudana-khichdi', name: 'Sabudana Khichdi', description: 'Tapioca pearl stir-fry with peanuts – fasting favourite.', cuisine: 'Indian', mealType: ['breakfast', 'snack'], calories: 300, protein: 6, carbs: 50, fat: 10, fiber: 2, prepTime: 15, cookTime: 10, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'gluten-free'], ingredients: [{ name: 'Sabudana', quantity: '1/2 cup', category: 'Grains' }, { name: 'Peanuts', quantity: '2 tbsp', category: 'Nuts' }, { name: 'Potato', quantity: '1 small', category: 'Produce' }], steps: ['Soak sabudana overnight.', 'Roast peanuts, fry potatoes.', 'Mix all and cook 5 min.'], emoji: '🍲', volumeFactor: 3, suitableFor: [], avoidFor: ['diabetes'] },
  { id: 'protein-smoothie', name: 'Banana Peanut Butter Smoothie', description: 'Thick protein-rich smoothie for quick mornings.', cuisine: 'Global', mealType: ['breakfast'], calories: 320, protein: 15, carbs: 38, fat: 14, fiber: 4, prepTime: 5, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'high-protein', 'no-cook'], ingredients: [{ name: 'Banana', quantity: '1', category: 'Produce' }, { name: 'Peanut butter', quantity: '2 tbsp', category: 'Pantry' }, { name: 'Milk', quantity: '1 cup', category: 'Dairy' }], steps: ['Blend all ingredients.', 'Add ice if desired.', 'Serve immediately.'], emoji: '🥤', volumeFactor: 4, suitableFor: [], avoidFor: [] },
  { id: 'methi-thepla', name: 'Methi Thepla', description: 'Gujarati fenugreek flatbread – travel-friendly breakfast.', cuisine: 'Indian', mealType: ['breakfast'], calories: 250, protein: 8, carbs: 38, fat: 8, fiber: 4, prepTime: 15, cookTime: 15, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'gujarati'], ingredients: [{ name: 'Wheat flour', quantity: '1 cup', category: 'Grains' }, { name: 'Methi leaves', quantity: '1/2 cup', category: 'Produce' }, { name: 'Yogurt', quantity: '2 tbsp', category: 'Dairy' }], steps: ['Knead dough with methi, spices, yogurt.', 'Roll thin and cook on tawa.', 'Serve with pickle or curd.'], emoji: '🫓', volumeFactor: 2, suitableFor: ['diabetes'], avoidFor: [] },
  { id: 'masala-dosa-lite', name: 'Masala Dosa (Lite)', description: 'Crispy dosa with light potato filling.', cuisine: 'Indian', mealType: ['breakfast'], calories: 290, protein: 8, carbs: 48, fat: 8, fiber: 3, prepTime: 10, cookTime: 15, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'south-indian'], ingredients: [{ name: 'Dosa batter', quantity: '1 cup', category: 'Grains' }, { name: 'Potato', quantity: '1 medium', category: 'Produce' }, { name: 'Mustard seeds', quantity: '1/4 tsp', category: 'Spices' }], steps: ['Boil and mash potato with spices.', 'Spread batter thin on tawa.', 'Add filling and fold.'], emoji: '🫓', volumeFactor: 3, suitableFor: [], avoidFor: ['diabetes'] },
  { id: 'egg-wrap', name: 'Egg & Veggie Wrap', description: 'Whole wheat wrap with scrambled egg and veggies.', cuisine: 'Global', mealType: ['breakfast'], calories: 300, protein: 16, carbs: 30, fat: 12, fiber: 4, prepTime: 5, cookTime: 8, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'high-protein', 'quick'], ingredients: [{ name: 'Whole wheat roti', quantity: '1', category: 'Grains' }, { name: 'Eggs', quantity: '2', category: 'Dairy' }, { name: 'Bell pepper', quantity: '1/4', category: 'Produce' }], steps: ['Scramble eggs with veggies.', 'Warm roti.', 'Roll filling inside.'], emoji: '🌯', volumeFactor: 2, suitableFor: [], avoidFor: ['cholesterol'] },
  { id: 'chia-pudding', name: 'Chia Seed Pudding', description: 'Omega-3 rich pudding with mixed berries.', cuisine: 'Global', mealType: ['breakfast', 'snack'], calories: 220, protein: 8, carbs: 25, fat: 10, fiber: 10, prepTime: 5, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegan', 'high-fiber', 'no-cook'], ingredients: [{ name: 'Chia seeds', quantity: '3 tbsp', category: 'Nuts' }, { name: 'Almond milk', quantity: '1 cup', category: 'Dairy' }, { name: 'Mixed berries', quantity: '1/4 cup', category: 'Produce' }], steps: ['Mix chia seeds with almond milk.', 'Refrigerate 4 hours or overnight.', 'Top with berries.'], emoji: '🍮', volumeFactor: 3, suitableFor: ['weight_loss', 'diabetes'], avoidFor: [] },
  { id: 'aloo-paratha-lite', name: 'Aloo Paratha (Low Oil)', description: 'Stuffed potato flatbread with minimal oil.', cuisine: 'Indian', mealType: ['breakfast'], calories: 280, protein: 7, carbs: 45, fat: 9, fiber: 3, prepTime: 15, cookTime: 10, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'north-indian'], ingredients: [{ name: 'Wheat flour', quantity: '1 cup', category: 'Grains' }, { name: 'Potato', quantity: '1 medium', category: 'Produce' }, { name: 'Oil', quantity: '1 tsp', category: 'Pantry' }], steps: ['Knead dough, boil and mash potato.', 'Stuff and roll paratha.', 'Cook on tawa with minimal oil.'], emoji: '🫓', volumeFactor: 2, suitableFor: [], avoidFor: ['diabetes'] },

  // ── LUNCH (15) ──
  { id: 'rajma-chawal', name: 'Rajma Chawal', description: 'Punjabi kidney bean curry with steamed rice.', cuisine: 'Indian', mealType: ['lunch'], calories: 450, protein: 16, carbs: 70, fat: 10, fiber: 12, prepTime: 15, cookTime: 30, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'high-fiber', 'north-indian'], ingredients: [{ name: 'Rajma', quantity: '1/2 cup', category: 'Pulses' }, { name: 'Rice', quantity: '3/4 cup', category: 'Grains' }, { name: 'Onion', quantity: '1', category: 'Produce' }, { name: 'Tomato', quantity: '2', category: 'Produce' }], steps: ['Pressure cook rajma.', 'Make gravy with onion-tomato.', 'Simmer rajma in gravy, serve with rice.'], emoji: '🍛', volumeFactor: 4, suitableFor: ['weight_loss'], avoidFor: ['ibs'] },
  { id: 'chicken-rice-bowl', name: 'Chicken Rice Bowl', description: 'Grilled chicken with brown rice and sautéed veggies.', cuisine: 'Global', mealType: ['lunch'], calories: 480, protein: 35, carbs: 50, fat: 14, fiber: 5, prepTime: 10, cookTime: 20, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'high-protein'], ingredients: [{ name: 'Chicken breast', quantity: '150g', category: 'Meat' }, { name: 'Brown rice', quantity: '3/4 cup', category: 'Grains' }, { name: 'Mixed vegetables', quantity: '1/2 cup', category: 'Produce' }], steps: ['Grill marinated chicken.', 'Cook brown rice.', 'Sauté vegetables, assemble bowl.'], emoji: '🍗', volumeFactor: 3, suitableFor: [], avoidFor: [] },
  { id: 'sambar-rice-thali', name: 'Sambar Rice Mini Thali', description: 'South Indian thali with sambar, rice, poriyal and rasam.', cuisine: 'Indian', mealType: ['lunch'], calories: 420, protein: 14, carbs: 65, fat: 10, fiber: 8, prepTime: 15, cookTime: 25, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'south-indian', 'balanced'], ingredients: [{ name: 'Rice', quantity: '3/4 cup', category: 'Grains' }, { name: 'Toor dal', quantity: '1/4 cup', category: 'Pulses' }, { name: 'Mixed vegetables', quantity: '1 cup', category: 'Produce' }, { name: 'Tamarind', quantity: '1/2 tsp', category: 'Pantry' }], steps: ['Cook sambar with dal and veggies.', 'Make simple rasam.', 'Stir-fry beans poriyal. Serve together.'], emoji: '🍛', volumeFactor: 5, suitableFor: ['diabetes'], avoidFor: [] },
  { id: 'egg-fried-rice', name: 'Egg Fried Rice', description: 'Quick Indo-Chinese style egg fried rice.', cuisine: 'Indo-Chinese', mealType: ['lunch', 'dinner'], calories: 380, protein: 14, carbs: 52, fat: 12, fiber: 3, prepTime: 5, cookTime: 10, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'quick'], ingredients: [{ name: 'Cooked rice', quantity: '1.5 cups', category: 'Grains' }, { name: 'Eggs', quantity: '2', category: 'Dairy' }, { name: 'Spring onion', quantity: '2', category: 'Produce' }, { name: 'Soy sauce', quantity: '1 tbsp', category: 'Pantry' }], steps: ['Scramble eggs, set aside.', 'Stir-fry veggies and rice on high heat.', 'Add soy sauce and eggs, toss.'], emoji: '🍚', volumeFactor: 3, suitableFor: [], avoidFor: ['hypertension'] },
  { id: 'chana-masala-roti', name: 'Chana Masala with Roti', description: 'Spiced chickpea curry with whole wheat roti.', cuisine: 'Indian', mealType: ['lunch'], calories: 400, protein: 15, carbs: 58, fat: 12, fiber: 10, prepTime: 10, cookTime: 20, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'high-fiber', 'budget'], ingredients: [{ name: 'Chickpeas', quantity: '1/2 cup', category: 'Pulses' }, { name: 'Wheat flour', quantity: '1 cup', category: 'Grains' }, { name: 'Onion', quantity: '1', category: 'Produce' }, { name: 'Tomato', quantity: '1', category: 'Produce' }], steps: ['Pressure cook chickpeas.', 'Make onion-tomato masala.', 'Simmer chana, serve with roti.'], emoji: '🍛', volumeFactor: 4, suitableFor: ['weight_loss'], avoidFor: ['ibs'] },
  { id: 'fish-curry-rice', name: 'Fish Curry with Rice', description: 'Coastal-style tangy fish curry with steamed rice.', cuisine: 'Indian', mealType: ['lunch', 'dinner'], calories: 420, protein: 28, carbs: 48, fat: 12, fiber: 3, prepTime: 10, cookTime: 20, difficulty: 'intermediate', servings: 1, tags: ['non-veg', 'high-protein', 'omega-3'], ingredients: [{ name: 'Fish', quantity: '200g', category: 'Seafood' }, { name: 'Rice', quantity: '3/4 cup', category: 'Grains' }, { name: 'Coconut milk', quantity: '1/4 cup', category: 'Pantry' }, { name: 'Tamarind', quantity: '1/2 tsp', category: 'Pantry' }], steps: ['Marinate fish.', 'Make coconut-tamarind gravy.', 'Cook fish in gravy, serve with rice.'], emoji: '🐟', volumeFactor: 4, suitableFor: [], avoidFor: ['cholesterol'] },
  { id: 'quinoa-salad-bowl', name: 'Quinoa Veggie Bowl', description: 'Protein-packed quinoa with roasted vegetables and tahini.', cuisine: 'Global', mealType: ['lunch'], calories: 380, protein: 14, carbs: 48, fat: 15, fiber: 8, prepTime: 10, cookTime: 15, difficulty: 'beginner', servings: 1, tags: ['vegan', 'high-fiber', 'healthy'], ingredients: [{ name: 'Quinoa', quantity: '1/2 cup', category: 'Grains' }, { name: 'Bell peppers', quantity: '1/2 cup', category: 'Produce' }, { name: 'Chickpeas', quantity: '1/4 cup', category: 'Pulses' }, { name: 'Tahini', quantity: '1 tbsp', category: 'Pantry' }], steps: ['Cook quinoa.', 'Roast vegetables.', 'Assemble bowl with tahini dressing.'], emoji: '🥗', volumeFactor: 4, suitableFor: ['diabetes', 'weight_loss'], avoidFor: [] },
  { id: 'paneer-bhurji-roti', name: 'Paneer Bhurji with Roti', description: 'Scrambled cottage cheese with spices and roti.', cuisine: 'Indian', mealType: ['lunch'], calories: 420, protein: 22, carbs: 40, fat: 18, fiber: 4, prepTime: 5, cookTime: 10, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'high-protein', 'north-indian'], ingredients: [{ name: 'Paneer', quantity: '150g', category: 'Dairy' }, { name: 'Wheat flour', quantity: '1 cup', category: 'Grains' }, { name: 'Onion', quantity: '1', category: 'Produce' }, { name: 'Tomato', quantity: '1', category: 'Produce' }], steps: ['Crumble paneer.', 'Sauté with onion, tomato, spices.', 'Serve with fresh roti.'], emoji: '🧀', volumeFactor: 3, suitableFor: [], avoidFor: [] },
  { id: 'mixed-veg-pulao', name: 'Mixed Vegetable Pulao', description: 'One-pot aromatic rice with seasonal vegetables.', cuisine: 'Indian', mealType: ['lunch'], calories: 350, protein: 8, carbs: 58, fat: 10, fiber: 5, prepTime: 10, cookTime: 20, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'one-pot'], ingredients: [{ name: 'Basmati rice', quantity: '3/4 cup', category: 'Grains' }, { name: 'Mixed vegetables', quantity: '1 cup', category: 'Produce' }, { name: 'Ghee', quantity: '1 tsp', category: 'Dairy' }, { name: 'Whole spices', quantity: '1 tsp', category: 'Spices' }], steps: ['Sauté veggies with whole spices.', 'Add rice and water.', 'Cook until done, fluff.'], emoji: '🍚', volumeFactor: 4, suitableFor: [], avoidFor: [] },
  { id: 'tuna-sandwich', name: 'Tuna Sandwich', description: 'Whole wheat tuna sandwich with lettuce and mustard.', cuisine: 'Global', mealType: ['lunch'], calories: 350, protein: 25, carbs: 32, fat: 12, fiber: 4, prepTime: 10, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'high-protein', 'no-cook', 'omega-3'], ingredients: [{ name: 'Canned tuna', quantity: '1 can', category: 'Seafood' }, { name: 'Whole wheat bread', quantity: '2 slices', category: 'Grains' }, { name: 'Lettuce', quantity: '2 leaves', category: 'Produce' }], steps: ['Mix tuna with light mayo and mustard.', 'Layer on bread with lettuce.', 'Serve.'], emoji: '🥪', volumeFactor: 2, suitableFor: [], avoidFor: [] },
  { id: 'dal-palak-rice', name: 'Dal Palak with Rice', description: 'Spinach-lentil curry packed with iron and protein.', cuisine: 'Indian', mealType: ['lunch'], calories: 400, protein: 16, carbs: 60, fat: 10, fiber: 8, prepTime: 10, cookTime: 20, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'high-fiber', 'iron-rich'], ingredients: [{ name: 'Toor dal', quantity: '1/2 cup', category: 'Pulses' }, { name: 'Spinach', quantity: '2 cups', category: 'Produce' }, { name: 'Rice', quantity: '3/4 cup', category: 'Grains' }], steps: ['Cook dal with turmeric.', 'Blanch and blend spinach.', 'Combine and temper. Serve with rice.'], emoji: '🥬', volumeFactor: 4, suitableFor: ['anemia'], avoidFor: [] },
  { id: 'mutton-biryani-lite', name: 'Mutton Biryani (Lite)', description: 'Lighter version of Hyderabadi biryani with less oil.', cuisine: 'Indian', mealType: ['lunch'], calories: 520, protein: 28, carbs: 62, fat: 16, fiber: 3, prepTime: 20, cookTime: 40, difficulty: 'advanced', servings: 1, tags: ['non-veg', 'high-protein', 'hyderabadi'], ingredients: [{ name: 'Mutton', quantity: '150g', category: 'Meat' }, { name: 'Basmati rice', quantity: '1 cup', category: 'Grains' }, { name: 'Yogurt', quantity: '1/4 cup', category: 'Dairy' }, { name: 'Onion', quantity: '2', category: 'Produce' }], steps: ['Marinate mutton in yogurt and spices.', 'Par-cook rice.', 'Layer and dum cook 30 min.'], emoji: '🍖', volumeFactor: 3, suitableFor: [], avoidFor: ['cholesterol', 'hypertension'] },
  { id: 'sweet-potato-bowl', name: 'Sweet Potato & Black Bean Bowl', description: 'Fibre-rich bowl with roasted sweet potato and beans.', cuisine: 'Global', mealType: ['lunch'], calories: 380, protein: 14, carbs: 60, fat: 8, fiber: 12, prepTime: 10, cookTime: 25, difficulty: 'beginner', servings: 1, tags: ['vegan', 'high-fiber', 'budget'], ingredients: [{ name: 'Sweet potato', quantity: '1 large', category: 'Produce' }, { name: 'Black beans', quantity: '1/2 cup', category: 'Pulses' }, { name: 'Lime', quantity: '1', category: 'Produce' }], steps: ['Roast cubed sweet potato.', 'Heat beans with spices.', 'Assemble bowl with lime dressing.'], emoji: '🍠', volumeFactor: 4, suitableFor: ['diabetes', 'weight_loss'], avoidFor: [] },
  { id: 'khichdi', name: 'Moong Dal Khichdi', description: 'Comfort food – rice and lentils cooked together.', cuisine: 'Indian', mealType: ['lunch', 'dinner'], calories: 350, protein: 12, carbs: 55, fat: 8, fiber: 6, prepTime: 5, cookTime: 20, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'budget', 'comfort-food'], ingredients: [{ name: 'Rice', quantity: '1/2 cup', category: 'Grains' }, { name: 'Moong dal', quantity: '1/4 cup', category: 'Pulses' }, { name: 'Ghee', quantity: '1 tsp', category: 'Dairy' }, { name: 'Vegetables', quantity: '1/2 cup', category: 'Produce' }], steps: ['Wash rice and dal.', 'Pressure cook with veggies and spices.', 'Add ghee tempering.'], emoji: '🍲', volumeFactor: 5, suitableFor: ['ibs', 'weight_loss'], avoidFor: [] },

  // ── DINNER (15) ──
  { id: 'palak-paneer-roti', name: 'Palak Paneer with Roti', description: 'Creamy spinach and paneer curry with whole wheat roti.', cuisine: 'Indian', mealType: ['dinner'], calories: 400, protein: 20, carbs: 38, fat: 18, fiber: 6, prepTime: 10, cookTime: 20, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'high-protein', 'iron-rich'], ingredients: [{ name: 'Paneer', quantity: '100g', category: 'Dairy' }, { name: 'Spinach', quantity: '2 cups', category: 'Produce' }, { name: 'Wheat flour', quantity: '1 cup', category: 'Grains' }], steps: ['Blanch and puree spinach.', 'Cook with paneer cubes.', 'Serve with roti.'], emoji: '🥬', volumeFactor: 4, suitableFor: ['anemia'], avoidFor: [] },
  { id: 'grilled-chicken-salad', name: 'Grilled Chicken Salad', description: 'High-protein salad with grilled chicken, greens and olive oil.', cuisine: 'Global', mealType: ['dinner'], calories: 320, protein: 30, carbs: 15, fat: 16, fiber: 4, prepTime: 10, cookTime: 15, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'high-protein', 'low-carb'], ingredients: [{ name: 'Chicken breast', quantity: '150g', category: 'Meat' }, { name: 'Mixed greens', quantity: '2 cups', category: 'Produce' }, { name: 'Olive oil', quantity: '1 tbsp', category: 'Pantry' }, { name: 'Cherry tomatoes', quantity: '5', category: 'Produce' }], steps: ['Grill seasoned chicken.', 'Assemble salad greens.', 'Slice chicken, drizzle olive oil.'], emoji: '🥗', volumeFactor: 4, suitableFor: ['weight_loss'], avoidFor: [] },
  { id: 'dal-makhani-rice', name: 'Dal Makhani with Rice', description: 'Rich black lentil curry slow-cooked to perfection.', cuisine: 'Indian', mealType: ['dinner'], calories: 480, protein: 16, carbs: 62, fat: 18, fiber: 8, prepTime: 15, cookTime: 40, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'north-indian', 'comfort-food'], ingredients: [{ name: 'Urad dal', quantity: '1/2 cup', category: 'Pulses' }, { name: 'Rajma', quantity: '2 tbsp', category: 'Pulses' }, { name: 'Butter', quantity: '1 tbsp', category: 'Dairy' }, { name: 'Rice', quantity: '3/4 cup', category: 'Grains' }], steps: ['Soak and pressure cook dals.', 'Simmer with tomato, butter, cream.', 'Cook low and slow 30 min. Serve with rice.'], emoji: '🍛', volumeFactor: 4, suitableFor: [], avoidFor: ['cholesterol'] },
  { id: 'tandoori-chicken-roti', name: 'Tandoori Chicken with Roti', description: 'Oven-baked tandoori chicken with mint chutney.', cuisine: 'Indian', mealType: ['dinner'], calories: 380, protein: 32, carbs: 30, fat: 14, fiber: 3, prepTime: 30, cookTime: 25, difficulty: 'intermediate', servings: 1, tags: ['non-veg', 'high-protein', 'north-indian'], ingredients: [{ name: 'Chicken leg', quantity: '2 pieces', category: 'Meat' }, { name: 'Yogurt', quantity: '1/2 cup', category: 'Dairy' }, { name: 'Wheat flour', quantity: '1 cup', category: 'Grains' }], steps: ['Marinate chicken in yogurt and spices 2h.', 'Bake at 200°C for 25 min.', 'Serve with roti and mint chutney.'], emoji: '🍗', volumeFactor: 3, suitableFor: [], avoidFor: [] },
  { id: 'mushroom-soup-bread', name: 'Mushroom Soup with Bread', description: 'Creamy mushroom soup with toasted whole wheat bread.', cuisine: 'Global', mealType: ['dinner'], calories: 280, protein: 10, carbs: 35, fat: 12, fiber: 4, prepTime: 5, cookTime: 20, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'light', 'comfort-food'], ingredients: [{ name: 'Mushrooms', quantity: '1 cup', category: 'Produce' }, { name: 'Milk', quantity: '1/2 cup', category: 'Dairy' }, { name: 'Bread', quantity: '2 slices', category: 'Grains' }], steps: ['Sauté mushrooms with garlic.', 'Add milk and blend partially.', 'Serve with toasted bread.'], emoji: '🍄', volumeFactor: 5, suitableFor: ['weight_loss'], avoidFor: [] },
  { id: 'keema-pav', name: 'Chicken Keema Pav', description: 'Spiced minced chicken served with soft pav bread.', cuisine: 'Indian', mealType: ['dinner'], calories: 420, protein: 28, carbs: 35, fat: 18, fiber: 3, prepTime: 10, cookTime: 20, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'high-protein'], ingredients: [{ name: 'Chicken mince', quantity: '200g', category: 'Meat' }, { name: 'Pav', quantity: '2', category: 'Grains' }, { name: 'Onion', quantity: '1', category: 'Produce' }, { name: 'Tomato', quantity: '1', category: 'Produce' }], steps: ['Cook mince with onion, tomato, spices.', 'Simmer until dry.', 'Serve with buttered pav.'], emoji: '🍖', volumeFactor: 3, suitableFor: [], avoidFor: [] },
  { id: 'veg-stir-fry-noodles', name: 'Vegetable Stir-Fry Noodles', description: 'Quick hakka noodles with colourful vegetables.', cuisine: 'Indo-Chinese', mealType: ['dinner'], calories: 360, protein: 10, carbs: 52, fat: 12, fiber: 4, prepTime: 10, cookTime: 10, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'quick'], ingredients: [{ name: 'Noodles', quantity: '1 pack', category: 'Grains' }, { name: 'Mixed vegetables', quantity: '1 cup', category: 'Produce' }, { name: 'Soy sauce', quantity: '1 tbsp', category: 'Pantry' }], steps: ['Boil and drain noodles.', 'Stir-fry vegetables.', 'Toss noodles with soy sauce.'], emoji: '🍜', volumeFactor: 3, suitableFor: [], avoidFor: ['hypertension'] },
  { id: 'moong-soup', name: 'Moong Dal Soup', description: 'Light protein soup perfect for a light dinner.', cuisine: 'Indian', mealType: ['dinner'], calories: 180, protein: 12, carbs: 25, fat: 3, fiber: 6, prepTime: 5, cookTime: 15, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'budget', 'light'], ingredients: [{ name: 'Moong dal', quantity: '1/2 cup', category: 'Pulses' }, { name: 'Turmeric', quantity: '1/4 tsp', category: 'Spices' }, { name: 'Lemon', quantity: '1/2', category: 'Produce' }], steps: ['Boil moong dal with turmeric.', 'Blend until smooth.', 'Add lemon juice and serve.'], emoji: '🥣', volumeFactor: 5, suitableFor: ['ibs', 'weight_loss'], avoidFor: [] },
  { id: 'egg-curry-roti', name: 'Egg Curry with Roti', description: 'Boiled eggs in onion-tomato gravy with roti.', cuisine: 'Indian', mealType: ['dinner'], calories: 380, protein: 20, carbs: 38, fat: 16, fiber: 4, prepTime: 10, cookTime: 15, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'high-protein', 'budget'], ingredients: [{ name: 'Eggs', quantity: '3', category: 'Dairy' }, { name: 'Wheat flour', quantity: '1 cup', category: 'Grains' }, { name: 'Onion', quantity: '1', category: 'Produce' }, { name: 'Tomato', quantity: '1', category: 'Produce' }], steps: ['Boil eggs, halve.', 'Make onion-tomato gravy.', 'Add eggs, simmer. Serve with roti.'], emoji: '🥚', volumeFactor: 3, suitableFor: [], avoidFor: ['cholesterol'] },
  { id: 'stuffed-capsicum', name: 'Stuffed Capsicum', description: 'Bell peppers stuffed with spiced potato and paneer.', cuisine: 'Indian', mealType: ['dinner'], calories: 300, protein: 12, carbs: 35, fat: 14, fiber: 5, prepTime: 15, cookTime: 20, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'healthy'], ingredients: [{ name: 'Capsicum', quantity: '2 large', category: 'Produce' }, { name: 'Paneer', quantity: '50g', category: 'Dairy' }, { name: 'Potato', quantity: '1 small', category: 'Produce' }], steps: ['Hollow out capsicums.', 'Mix paneer, potato, spices.', 'Stuff and bake/cook covered 15 min.'], emoji: '🫑', volumeFactor: 4, suitableFor: ['weight_loss'], avoidFor: [] },
  { id: 'prawn-masala', name: 'Prawn Masala with Rice', description: 'Coastal spicy prawn curry.', cuisine: 'Indian', mealType: ['dinner'], calories: 400, protein: 30, carbs: 45, fat: 12, fiber: 3, prepTime: 10, cookTime: 15, difficulty: 'intermediate', servings: 1, tags: ['non-veg', 'high-protein', 'omega-3'], ingredients: [{ name: 'Prawns', quantity: '200g', category: 'Seafood' }, { name: 'Rice', quantity: '3/4 cup', category: 'Grains' }, { name: 'Coconut', quantity: '2 tbsp', category: 'Pantry' }], steps: ['Clean prawns.', 'Make coconut masala.', 'Cook prawns in masala. Serve with rice.'], emoji: '🦐', volumeFactor: 3, suitableFor: [], avoidFor: ['cholesterol'] },
  { id: 'mixed-dal-roti', name: 'Panchmel Dal with Roti', description: 'Five-lentil mix curry – Rajasthani speciality.', cuisine: 'Indian', mealType: ['dinner'], calories: 380, protein: 18, carbs: 50, fat: 10, fiber: 10, prepTime: 15, cookTime: 25, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'high-protein', 'high-fiber'], ingredients: [{ name: 'Mixed dals', quantity: '1/2 cup', category: 'Pulses' }, { name: 'Wheat flour', quantity: '1 cup', category: 'Grains' }, { name: 'Ghee', quantity: '1 tsp', category: 'Dairy' }], steps: ['Soak and cook mixed dals.', 'Add spices and ghee tadka.', 'Serve with hot roti.'], emoji: '🍛', volumeFactor: 4, suitableFor: ['anemia'], avoidFor: [] },
  { id: 'tofu-stir-fry', name: 'Tofu & Veggie Stir-Fry', description: 'High-protein tofu with colourful vegetables.', cuisine: 'Asian', mealType: ['dinner'], calories: 280, protein: 18, carbs: 20, fat: 14, fiber: 5, prepTime: 10, cookTime: 10, difficulty: 'beginner', servings: 1, tags: ['vegan', 'high-protein', 'low-carb'], ingredients: [{ name: 'Firm tofu', quantity: '200g', category: 'Produce' }, { name: 'Broccoli', quantity: '1/2 cup', category: 'Produce' }, { name: 'Soy sauce', quantity: '1 tbsp', category: 'Pantry' }], steps: ['Press and cube tofu.', 'Stir-fry with vegetables.', 'Add soy sauce and serve.'], emoji: '🥘', volumeFactor: 3, suitableFor: ['weight_loss'], avoidFor: [] },
  { id: 'chicken-soup', name: 'Chicken Clear Soup', description: 'Light and nourishing chicken broth with vegetables.', cuisine: 'Global', mealType: ['dinner'], calories: 180, protein: 18, carbs: 10, fat: 8, fiber: 2, prepTime: 5, cookTime: 25, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'low-calorie', 'light'], ingredients: [{ name: 'Chicken', quantity: '100g', category: 'Meat' }, { name: 'Mixed vegetables', quantity: '1/2 cup', category: 'Produce' }, { name: 'Ginger', quantity: '1 inch', category: 'Produce' }], steps: ['Boil chicken with ginger.', 'Add chopped vegetables.', 'Season and serve hot.'], emoji: '🍲', volumeFactor: 5, suitableFor: ['weight_loss', 'ibs'], avoidFor: [] },

  // ── SNACKS (15) ──
  { id: 'roasted-chana', name: 'Roasted Chana', description: 'Crunchy protein-rich roasted chickpeas.', cuisine: 'Indian', mealType: ['snack'], calories: 120, protein: 7, carbs: 18, fat: 3, fiber: 4, prepTime: 2, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'budget', 'high-protein'], ingredients: [{ name: 'Roasted chana', quantity: '1/4 cup', category: 'Pulses' }], steps: ['Buy roasted chana.', 'Sprinkle chaat masala.', 'Eat!'], emoji: '🫘', volumeFactor: 1, suitableFor: ['diabetes', 'weight_loss'], avoidFor: [] },
  { id: 'fruit-chaat', name: 'Fruit Chaat', description: 'Mixed seasonal fruits with chaat masala and lime.', cuisine: 'Indian', mealType: ['snack'], calories: 130, protein: 2, carbs: 30, fat: 1, fiber: 4, prepTime: 5, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegan', 'no-cook', 'low-fat'], ingredients: [{ name: 'Mixed fruits', quantity: '1 cup', category: 'Produce' }, { name: 'Chaat masala', quantity: '1/4 tsp', category: 'Spices' }, { name: 'Lime', quantity: '1/2', category: 'Produce' }], steps: ['Cut fruits.', 'Add chaat masala and lime.', 'Toss and serve.'], emoji: '🍉', volumeFactor: 4, suitableFor: ['weight_loss'], avoidFor: ['diabetes'] },
  { id: 'boiled-egg-snack', name: 'Boiled Eggs (2)', description: 'Simple high-protein snack – 2 boiled eggs.', cuisine: 'Global', mealType: ['snack'], calories: 140, protein: 12, carbs: 1, fat: 10, fiber: 0, prepTime: 2, cookTime: 10, difficulty: 'beginner', servings: 1, tags: ['non-veg', 'high-protein', 'budget', 'keto'], ingredients: [{ name: 'Eggs', quantity: '2', category: 'Dairy' }], steps: ['Boil eggs 10 minutes.', 'Peel.', 'Season with salt and pepper.'], emoji: '🥚', volumeFactor: 1, suitableFor: ['weight_loss'], avoidFor: ['cholesterol'] },
  { id: 'makhana-snack', name: 'Roasted Makhana', description: 'Fox nuts roasted with ghee and spices.', cuisine: 'Indian', mealType: ['snack'], calories: 110, protein: 4, carbs: 18, fat: 3, fiber: 2, prepTime: 2, cookTime: 5, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'budget', 'low-calorie'], ingredients: [{ name: 'Makhana', quantity: '1/2 cup', category: 'Nuts' }, { name: 'Ghee', quantity: '1/2 tsp', category: 'Dairy' }], steps: ['Dry roast makhana.', 'Add ghee and salt.', 'Cool and eat.'], emoji: '🌰', volumeFactor: 2, suitableFor: ['diabetes', 'weight_loss'], avoidFor: [] },
  { id: 'sprouts-salad', name: 'Sprouts Salad', description: 'Protein-packed sprouted moong salad.', cuisine: 'Indian', mealType: ['snack'], calories: 150, protein: 10, carbs: 20, fat: 3, fiber: 6, prepTime: 5, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegan', 'high-protein', 'no-cook'], ingredients: [{ name: 'Sprouted moong', quantity: '1/2 cup', category: 'Pulses' }, { name: 'Onion', quantity: '1 small', category: 'Produce' }, { name: 'Lemon', quantity: '1/2', category: 'Produce' }], steps: ['Mix sprouts with chopped onion, tomato.', 'Add lemon juice and chaat masala.', 'Serve fresh.'], emoji: '🌱', volumeFactor: 3, suitableFor: ['diabetes', 'weight_loss'], avoidFor: ['ibs'] },
  { id: 'greek-yogurt-bowl', name: 'Greek Yogurt with Nuts', description: 'Thick yogurt topped with almonds and honey.', cuisine: 'Global', mealType: ['snack'], calories: 180, protein: 14, carbs: 15, fat: 8, fiber: 2, prepTime: 3, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'high-protein', 'probiotic'], ingredients: [{ name: 'Greek yogurt', quantity: '1 cup', category: 'Dairy' }, { name: 'Almonds', quantity: '5', category: 'Nuts' }, { name: 'Honey', quantity: '1 tsp', category: 'Pantry' }], steps: ['Pour yogurt in bowl.', 'Top with chopped almonds.', 'Drizzle honey.'], emoji: '🥛', volumeFactor: 3, suitableFor: [], avoidFor: [] },
  { id: 'peanut-chikki', name: 'Peanut Chikki (Small)', description: 'Traditional peanut-jaggery bar – quick energy.', cuisine: 'Indian', mealType: ['snack'], calories: 160, protein: 5, carbs: 18, fat: 8, fiber: 2, prepTime: 0, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'budget'], ingredients: [{ name: 'Peanut chikki', quantity: '1 bar', category: 'Pantry' }], steps: ['Unwrap and eat.'], emoji: '🥜', volumeFactor: 1, suitableFor: [], avoidFor: ['diabetes'] },
  { id: 'cucumber-hummus', name: 'Cucumber Sticks with Hummus', description: 'Fresh cucumber with chickpea hummus dip.', cuisine: 'Global', mealType: ['snack'], calories: 130, protein: 6, carbs: 14, fat: 6, fiber: 4, prepTime: 5, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegan', 'low-calorie', 'no-cook'], ingredients: [{ name: 'Cucumber', quantity: '1', category: 'Produce' }, { name: 'Hummus', quantity: '3 tbsp', category: 'Pantry' }], steps: ['Slice cucumber into sticks.', 'Serve with hummus.'], emoji: '🥒', volumeFactor: 4, suitableFor: ['diabetes', 'weight_loss'], avoidFor: [] },
  { id: 'banana-walnut', name: 'Banana with Walnuts', description: 'Quick natural energy – banana with omega-3 walnuts.', cuisine: 'Global', mealType: ['snack'], calories: 170, protein: 4, carbs: 28, fat: 6, fiber: 3, prepTime: 2, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegan', 'no-cook', 'quick'], ingredients: [{ name: 'Banana', quantity: '1', category: 'Produce' }, { name: 'Walnuts', quantity: '4', category: 'Nuts' }], steps: ['Peel banana.', 'Eat with walnuts.'], emoji: '🍌', volumeFactor: 2, suitableFor: [], avoidFor: [] },
  { id: 'paneer-tikka-snack', name: 'Paneer Tikka (4 pcs)', description: 'Grilled spiced paneer cubes – protein-rich snack.', cuisine: 'Indian', mealType: ['snack'], calories: 200, protein: 14, carbs: 8, fat: 14, fiber: 1, prepTime: 15, cookTime: 10, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'high-protein', 'keto'], ingredients: [{ name: 'Paneer', quantity: '100g', category: 'Dairy' }, { name: 'Yogurt', quantity: '2 tbsp', category: 'Dairy' }, { name: 'Spices', quantity: '1 tsp', category: 'Spices' }], steps: ['Cube paneer, marinate in yogurt-spice mix.', 'Grill or air-fry 10 min.', 'Serve with chutney.'], emoji: '🧀', volumeFactor: 2, suitableFor: [], avoidFor: [] },
  { id: 'popcorn', name: 'Air-Popped Popcorn', description: 'Light, high-volume snack with minimal calories.', cuisine: 'Global', mealType: ['snack'], calories: 90, protein: 3, carbs: 16, fat: 2, fiber: 3, prepTime: 2, cookTime: 3, difficulty: 'beginner', servings: 1, tags: ['vegan', 'low-calorie', 'budget'], ingredients: [{ name: 'Popcorn kernels', quantity: '2 tbsp', category: 'Grains' }], steps: ['Pop kernels in microwave or pot.', 'Season with salt.'], emoji: '🍿', volumeFactor: 5, suitableFor: ['weight_loss'], avoidFor: [] },
  { id: 'dates-almonds', name: 'Dates with Almonds', description: 'Natural energy balls – 3 dates stuffed with almonds.', cuisine: 'Global', mealType: ['snack'], calories: 150, protein: 4, carbs: 28, fat: 4, fiber: 3, prepTime: 2, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegan', 'no-cook', 'iron-rich'], ingredients: [{ name: 'Dates', quantity: '3', category: 'Produce' }, { name: 'Almonds', quantity: '3', category: 'Nuts' }], steps: ['Pit dates.', 'Stuff with almond.', 'Eat.'], emoji: '🌴', volumeFactor: 1, suitableFor: ['anemia'], avoidFor: ['diabetes'] },
  { id: 'dhokla', name: 'Dhokla (4 pcs)', description: 'Steamed gram flour cake – light Gujarati snack.', cuisine: 'Indian', mealType: ['snack'], calories: 160, protein: 8, carbs: 24, fat: 4, fiber: 3, prepTime: 10, cookTime: 15, difficulty: 'intermediate', servings: 1, tags: ['vegetarian', 'steamed', 'gujarati'], ingredients: [{ name: 'Besan', quantity: '1/2 cup', category: 'Grains' }, { name: 'Yogurt', quantity: '1/4 cup', category: 'Dairy' }, { name: 'Sugar', quantity: '1 tsp', category: 'Pantry' }], steps: ['Mix besan, yogurt, Eno.', 'Steam 15 min.', 'Temper and cut into pieces.'], emoji: '🟨', volumeFactor: 3, suitableFor: ['weight_loss'], avoidFor: [] },
  { id: 'trail-mix', name: 'Trail Mix (Dry Fruits)', description: 'Mixed nuts, seeds and dried cranberries.', cuisine: 'Global', mealType: ['snack'], calories: 200, protein: 6, carbs: 18, fat: 14, fiber: 3, prepTime: 0, cookTime: 0, difficulty: 'beginner', servings: 1, tags: ['vegan', 'healthy-fats', 'no-cook'], ingredients: [{ name: 'Mixed nuts', quantity: '1/4 cup', category: 'Nuts' }, { name: 'Seeds', quantity: '1 tbsp', category: 'Nuts' }, { name: 'Cranberries', quantity: '1 tbsp', category: 'Produce' }], steps: ['Mix all.', 'Portion into a small bowl.'], emoji: '🥜', volumeFactor: 1, suitableFor: [], avoidFor: [] },
  { id: 'corn-chaat', name: 'Masala Corn', description: 'Spiced buttered sweet corn – street-style.', cuisine: 'Indian', mealType: ['snack'], calories: 140, protein: 4, carbs: 25, fat: 4, fiber: 3, prepTime: 2, cookTime: 5, difficulty: 'beginner', servings: 1, tags: ['vegetarian', 'budget'], ingredients: [{ name: 'Sweet corn', quantity: '1 cup', category: 'Produce' }, { name: 'Butter', quantity: '1/2 tsp', category: 'Dairy' }, { name: 'Chaat masala', quantity: '1/4 tsp', category: 'Spices' }], steps: ['Boil or microwave corn.', 'Add butter and chaat masala.', 'Squeeze lime.'], emoji: '🌽', volumeFactor: 3, suitableFor: [], avoidFor: [] },
];

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find(r => r.id === id);
}

export function getRecipesByMealType(type: string): Recipe[] {
  return recipes.filter(r => r.mealType.includes(type as any));
}

export function filterRecipes(opts: {
  mealType?: string;
  tags?: string[];
  maxCalories?: number;
  maxPrepTime?: number;
  difficulty?: string;
  cuisines?: string[];
  excludeIds?: string[];
}): Recipe[] {
  return recipes.filter(r => {
    if (opts.mealType && !r.mealType.includes(opts.mealType as any)) return false;
    if (opts.tags?.length) {
      const hasConflict = opts.tags.some(tag => {
        if (tag === 'vegetarian') return r.tags.includes('non-veg');
        if (tag === 'vegan') return r.tags.includes('non-veg') || r.ingredients.some(i => ['Dairy', 'Meat', 'Seafood'].includes(i.category));
        return false;
      });
      if (hasConflict) return false;
    }
    if (opts.maxCalories && r.calories > opts.maxCalories) return false;
    if (opts.maxPrepTime && (r.prepTime + r.cookTime) > opts.maxPrepTime) return false;
    if (opts.difficulty && r.difficulty !== opts.difficulty) return false;
    if (opts.cuisines?.length && !opts.cuisines.includes(r.cuisine)) return false;
    if (opts.excludeIds?.length && opts.excludeIds.includes(r.id)) return false;
    return true;
  });
}
